//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMCategoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMCategoryMaster()
        {
            this.ADMRoles = new HashSet<ADMRoles>();
            this.ADMLinkCategory = new HashSet<ADMLinkCategory>();
        }
    
        public int CategoryMasterID { get; set; }
        public string CategoryMasterNameAr { get; set; }
        public string CategoryMasterNameEn { get; set; }
        public string Notes { get; set; }
        public Nullable<int> FKModuleId { get; set; }
        public Nullable<int> OrderNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMRoles> ADMRoles { get; set; }
        public virtual ADMModules ADMModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMLinkCategory> ADMLinkCategory { get; set; }
    }
}
