//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMLinkCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMLinkCategory()
        {
            this.ADMLinks = new HashSet<ADMLinks>();
        }
    
        public int LinkCategoryID { get; set; }
        public string Code { get; set; }
        public string LinkCategoryAName { get; set; }
        public string LinkCategoryEName { get; set; }
        public string Notes { get; set; }
        public int FKCategoryMasterID { get; set; }
        public Nullable<int> OrderNo { get; set; }
    
        public virtual ADMCategoryMaster ADMCategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMLinks> ADMLinks { get; set; }
    }
}
