//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMLinks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMLinks()
        {
            this.ADMRoleLink = new HashSet<ADMRoleLink>();
        }
    
        public int LinksID { get; set; }
        public string LinksAName { get; set; }
        public string LinksEName { get; set; }
        public string Url { get; set; }
        public string Notes { get; set; }
        public string LinkIcon { get; set; }
        public bool ActiveLink { get; set; }
        public bool MenuLink { get; set; }
        public int FKLinkCategoryID { get; set; }
        public int FKModuleID { get; set; }
        public Nullable<int> OrderNo { get; set; }
    
        public virtual ADMLinkCategory ADMLinkCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMRoleLink> ADMRoleLink { get; set; }
        public virtual ADMModules ADMModules { get; set; }
    }
}
