//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMModules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMModules()
        {
            this.ADMCategoryMaster = new HashSet<ADMCategoryMaster>();
            this.ADMLinks = new HashSet<ADMLinks>();
            this.ADMUsers = new HashSet<ADMUsers>();
        }
    
        public int ModuleID { get; set; }
        public string Code { get; set; }
        public string ModuleAName { get; set; }
        public string ModuleEName { get; set; }
        public string Notes { get; set; }
        public string ModuleUrl { get; set; }
        public Nullable<int> OrderNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMCategoryMaster> ADMCategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMLinks> ADMLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMUsers> ADMUsers { get; set; }
    }
}
