//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMRoleLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMRoleLink()
        {
            this.ADMRoleLinkOptions = new HashSet<ADMRoleLinkOptions>();
        }
    
        public int RoleLinkID { get; set; }
        public int FKRoleID { get; set; }
        public int FKLinkID { get; set; }
        public Nullable<int> Arrange { get; set; }
    
        public virtual ADMLinks ADMLinks { get; set; }
        public virtual ADMRoles ADMRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMRoleLinkOptions> ADMRoleLinkOptions { get; set; }
    }
}
