//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMReportPages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMReportPages()
        {
            this.ADMReportsCategory = new HashSet<ADMReportsCategory>();
        }
    
        public int RPID { get; set; }
        public string RPCode { get; set; }
        public string RPNameEn { get; set; }
        public string RPNameAr { get; set; }
        public string RPNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMReportsCategory> ADMReportsCategory { get; set; }
    }
}
