//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMRoleLinkOptions
    {
        public long RoleLinkOptionID { get; set; }
        public int FKRoleLinkID { get; set; }
        public int FKOptionID { get; set; }
    
        public virtual ADMOption ADMOption { get; set; }
        public virtual ADMRoleLink ADMRoleLink { get; set; }
    }
}
