//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMReportsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMReportsCategory()
        {
            this.ADMReports = new HashSet<ADMReports>();
        }
    
        public int RCID { get; set; }
        public string RCCode { get; set; }
        public string RCNameEn { get; set; }
        public string RCNameAr { get; set; }
        public string RCNotes { get; set; }
        public int FKReportPageID { get; set; }
    
        public virtual ADMReportPages ADMReportPages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMReports> ADMReports { get; set; }
    }
}
