//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMRoles()
        {
            this.ADMRoleLink = new HashSet<ADMRoleLink>();
            this.ADMUserRoles = new HashSet<ADMUserRoles>();
        }
    
        public int RoleID { get; set; }
        public string Code { get; set; }
        public string RoleAName { get; set; }
        public string RoleEName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> FKModuleID { get; set; }
        public int UserType { get; set; }
    
        public virtual ADMCategoryMaster ADMCategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMRoleLink> ADMRoleLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMUserRoles> ADMUserRoles { get; set; }
    }
}
