//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMReports
    {
        public long ReportsID { get; set; }
        public string ReportsCode { get; set; }
        public string ReportsNameEn { get; set; }
        public string ReportsNameAr { get; set; }
        public string ReportsNotes { get; set; }
        public string ReportUrl { get; set; }
        public int FKRreportCategoryID { get; set; }
    
        public virtual ADMReportsCategory ADMReportsCategory { get; set; }
    }
}
