//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMUserSettings
    {
        public long UserSettingsID { get; set; }
        public Nullable<int> FKUserID { get; set; }
        public string SettingsName { get; set; }
        public string SettingsValue { get; set; }
        public string Remarks { get; set; }
    
        public virtual ADMUsers ADMUsers { get; set; }
    }
}
