//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMUsers()
        {
            this.ADMUserRoles = new HashSet<ADMUserRoles>();
            this.ADMUserSettings = new HashSet<ADMUserSettings>();
        }
    
        public int UserID { get; set; }
        public string Code { get; set; }
        public string Password { get; set; }
        public string EName { get; set; }
        public string AName { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsRemoved { get; set; }
        public Nullable<bool> PreferedLanguage { get; set; }
        public Nullable<int> DefaultModule { get; set; }
    
        public virtual ADMModules ADMModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMUserRoles> ADMUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADMUserSettings> ADMUserSettings { get; set; }
    }
}
