//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachedFiles
    {
        public long FileID { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public string FileExtention { get; set; }
        public string FileUrl { get; set; }
        public string FileSize { get; set; }
        public bool IsUrl { get; set; }
        public int FKTransTypeID { get; set; }
        public long FKTransID { get; set; }
        public string Keywords { get; set; }
    
        public virtual AttachFileTransTypes AttachFileTransTypes { get; set; }
    }
}
