//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachFileTransTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttachFileTransTypes()
        {
            this.AttachedFiles = new HashSet<AttachedFiles>();
        }
    
        public int TransTypeID { get; set; }
        public string TransName { get; set; }
        public Nullable<int> FKModuleID { get; set; }
        public string TableName { get; set; }
        public string PageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachedFiles> AttachedFiles { get; set; }
    }
}
