//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
         public company_profile()
         {
            this.equipmentslist = new hashset<equipmentslist>();
          this.rssmaster = new hashset<rssmaster>();
             this.workordertimesheet = new hashset<workordertimesheet>();
        }
    
        public int ProfileID { get; set; }
        public string CompanyName { get; set; }
        public string Location { get; set; }
        public string GM_Name { get; set; }
        public string Telephone_No { get; set; }
        public string Email { get; set; }
        public string website { get; set; }
        public string Address { get; set; }
        public string POBox { get; set; }
		public string Image { get; set; }
        //public bool IsLocked { get; set; }
    
        // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        // public virtual ICollection<EquipmentsList> EquipmentsList { get; set; }
        // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        // public virtual ICollection<RSSMaster> RSSMaster { get; set; }
        // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        // public virtual ICollection<WorkOrderTimeSheet> WorkOrderTimeSheet { get; set; }
    }
}
