//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorsList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractorsList()
        {
            this.ProjectsList = new HashSet<ProjectsList>();
        }
    
        public int ContractorID { get; set; }
        public string ContractorCode { get; set; }
        public string ContractorName { get; set; }
        public string ContractorCarrier { get; set; }
        public string Location { get; set; }
        public string GMName { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public string website { get; set; }
        public string Address { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> ContractorType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsList> ProjectsList { get; set; }
    }
}
