//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnquiryDetails()
        {
            this.QuotationDetails = new HashSet<QuotationDetails>();
        }
    
        public long EnquiryDetailsID { get; set; }
        public long FKEnquiryMasterID { get; set; }
        public Nullable<int> FKMaterialTypeID { get; set; }
        public Nullable<int> FKMaterialDetailsID { get; set; }
        public int FKTestID { get; set; }
        public int FKPriceUnitID { get; set; }
        public string Remarks { get; set; }
    
        public virtual EnquiryMaster EnquiryMaster { get; set; }
        public virtual MaterialsDetails MaterialsDetails { get; set; }
        public virtual MaterialsTypes MaterialsTypes { get; set; }
        public virtual PriceUnitList PriceUnitList { get; set; }
        public virtual TestsList TestsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetails> QuotationDetails { get; set; }
    }
}
