//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnquiryMaster()
        {
            this.EnquiryDetails = new HashSet<EnquiryDetails>();
            this.QuotationMaster = new HashSet<QuotationMaster>();
        }
    
        public long EnquiryMasterID { get; set; }
        public string EnquiryCode { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public int FKCustomerID { get; set; }
        public int FKProjectID { get; set; }
        public Nullable<int> EnquiryMethodID { get; set; }
        public string CustomerReference { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string ContactJobTitle { get; set; }
        public string ContactEmail { get; set; }
        public string Remarks { get; set; }
        public string EnterdBy { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
    
        public virtual CustomersList CustomersList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryDetails> EnquiryDetails { get; set; }
        public virtual ProjectsList ProjectsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationMaster> QuotationMaster { get; set; }
    }
}
