//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentsList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentsList()
        {
            this.TestEquipments = new HashSet<TestEquipments>();
        }
    
        public int EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public int FKLabID { get; set; }
        public Nullable<System.DateTime> CalibrationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int FKEmpID { get; set; }
        public string CalibratedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual EmployeesList EmployeesList { get; set; }
        public virtual LabsList LabsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestEquipments> TestEquipments { get; set; }
    }
}
