//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.PaymentDetails = new HashSet<PaymentDetails>();
            this.SampleReceiveTestInvoice = new HashSet<SampleReceiveTestInvoice>();
            this.WorkOrderInvoice = new HashSet<WorkOrderInvoice>();
        }
    
        public long InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceRefNo { get; set; }
        public long FKJobOrderMasterID { get; set; }
        public Nullable<decimal> SRTTotal { get; set; }
        public Nullable<decimal> TSTotal { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<decimal> Disount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string ProvideDescription { get; set; }
        public Nullable<System.DateTime> InvoiceStartDate { get; set; }
        public Nullable<System.DateTime> InvoiceEndDate { get; set; }
    
        public virtual JobOrderMaster JobOrderMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetails> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleReceiveTestInvoice> SampleReceiveTestInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderInvoice> WorkOrderInvoice { get; set; }
    }
}
