//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetails
    {
        public long PaymentDetID { get; set; }
        public long FKPaymentID { get; set; }
        public long FKInvoiceId { get; set; }
        public decimal PaidAmount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual PaymentMaster PaymentMaster { get; set; }
    }
}
