//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuotationMaster()
        {
            this.JobOrderMaster = new HashSet<JobOrderMaster>();
            this.QuotationDetails = new HashSet<QuotationDetails>();
        }
    
        public long QuotationMasterID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<long> FKEnquiryMasterID { get; set; }
        public int FKCustomerID { get; set; }
        public int FKProjectID { get; set; }
        public string Remarks { get; set; }
        public bool IsClosed { get; set; }
        public bool IsActive { get; set; }
        public int StatusID { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> FKTermsConditionsID { get; set; }
        public string QuotationNo { get; set; }
        public bool ShowTotal { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsAddedTojo { get; set; }
    
        public virtual CustomersList CustomersList { get; set; }
        public virtual EnquiryMaster EnquiryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOrderMaster> JobOrderMaster { get; set; }
        public virtual ProjectsList ProjectsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationDetails> QuotationDetails { get; set; }
        public virtual TermsConditionList TermsConditionList { get; set; }
    }
}
