//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuotationDetails()
        {
            this.JobOrderDetails = new HashSet<JobOrderDetails>();
            this.QuotationWorkOrderList = new HashSet<QuotationWorkOrderList>();
        }
    
        public long QuotationDetailsID { get; set; }
        public long FKQuotationMasterID { get; set; }
        public int FKTestID { get; set; }
        public int FKPriceUnitID { get; set; }
        public Nullable<long> FKEnquiryDetailsID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FKMaterialTypeID { get; set; }
        public Nullable<int> FKMaterialDetailsID { get; set; }
    
        public virtual EnquiryDetails EnquiryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOrderDetails> JobOrderDetails { get; set; }
        public virtual MaterialsDetails MaterialsDetails { get; set; }
        public virtual MaterialsTypes MaterialsTypes { get; set; }
        public virtual PriceUnitList PriceUnitList { get; set; }
        public virtual QuotationMaster QuotationMaster { get; set; }
        public virtual TestsList TestsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationWorkOrderList> QuotationWorkOrderList { get; set; }
    }
}
