//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSSMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSSMaster()
        {
            this.RSSDetails = new HashSet<RSSDetails>();
            this.SampleReceiveList = new HashSet<SampleReceiveList>();
        }
    
        public long RSSMasterId { get; set; }
        public long FKJobOrderMasterID { get; set; }
        public string RSSNumber { get; set; }
        public System.DateTime RSSDate { get; set; }
        public string ContactPersonAtSite { get; set; }
        public string ContactMobile { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestBy { get; set; }
        public Nullable<System.DateTime> RequestTestDate { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
        public string SiteLocation { get; set; }
        public Nullable<int> FkEmpId { get; set; }
        public string Note { get; set; }
        public string ReportedBy { get; set; }
        public Nullable<bool> IsSampled { get; set; }
    
        public virtual EmployeesList EmployeesList { get; set; }
        public virtual JobOrderMaster JobOrderMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSDetails> RSSDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleReceiveList> SampleReceiveList { get; set; }
    }
}
