//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleReceiveTestInvoice
    {
        public long SampleReceiveTestInvoiceID { get; set; }
        public long FkInvoiceId { get; set; }
        public long FkSampleReceiveTestID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual SampleReceiveTestList SampleReceiveTestList { get; set; }
    }
}
