//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleReceiveTestList
    {
        public int RowStatus { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsSelected { get; set; }
        public decimal MinQty { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SampleReceiveTestList()
        {
            this.SampleReceiveTestInvoice = new HashSet<SampleReceiveTestInvoice>();
        }
    
        public long SampleReceiveTestID { get; set; }
        public Nullable<long> FKSampleID { get; set; }
        public Nullable<int> FKTestID { get; set; }
        public Nullable<int> FKPriceUnitID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public bool Witness { get; set; }
        public string WitnessName { get; set; }
        public bool Subcontract { get; set; }
        public Nullable<int> FKSubContractorID { get; set; }
        public string Remarks { get; set; }
        public bool Inactive { get; set; }
        public bool IsInvoiced { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<long> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ReportNumber { get; set; }
    
        public virtual PriceUnitList PriceUnitList { get; set; }
        public virtual SampleReceiveList SampleReceiveList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleReceiveTestInvoice> SampleReceiveTestInvoice { get; set; }
        public virtual SubcontractorsList SubcontractorsList { get; set; }
        public virtual TestsList TestsList { get; set; }
    }
}
