//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleReceiveList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SampleReceiveList()
        {
            this.SampleReceiveMaterialCustomField = new HashSet<SampleReceiveMaterialCustomField>();
            this.SampleReceiveMaterialTableCustomField = new HashSet<SampleReceiveMaterialTableCustomField>();
            this.SampleReceiveTestList = new HashSet<SampleReceiveTestList>();
        }
    
        public long SampleID { get; set; }
        public string SampleNo { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<long> FKJobOrderMasterID { get; set; }
        public Nullable<int> FKCustomerID { get; set; }
        public Nullable<long> FKRSSMasterId { get; set; }
        public Nullable<int> FKProjectID { get; set; }
        public string ConsultantName { get; set; }
        public string ConsultantMobile { get; set; }
        public string SiteContactPerson { get; set; }
        public string SiteContactMobile { get; set; }
        public string DelivererName { get; set; }
        public string DelivererMobile { get; set; }
        public string Supplier { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> SamplingDate { get; set; }
        public string SampleDescription { get; set; }
        public string SampleLocation { get; set; }
        public string SampledByID { get; set; }
        public string SampledByName { get; set; }
        public string SiteRefNo { get; set; }
        public string SampleBroughtInByID { get; set; }
        public string SampleBroughtInByName { get; set; }
        public string LayerNo { get; set; }
        public Nullable<int> FKMaterialTypeID { get; set; }
        public Nullable<int> FKMaterialDetailsID { get; set; }
        public string MaterialClass { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<int> FKPriceUnitID { get; set; }
        public Nullable<int> RetentionPeriod { get; set; }
        public string SampleCondition { get; set; }
        public string ConditionDetails { get; set; }
        public Nullable<System.DateTime> SampleBroughtInDate { get; set; }
        public Nullable<decimal> SampleTemperature { get; set; }
        public string ReceiveByName { get; set; }
    
        public virtual CustomersList CustomersList { get; set; }
        public virtual JobOrderMaster JobOrderMaster { get; set; }
        public virtual MaterialsDetails MaterialsDetails { get; set; }
        public virtual MaterialsTypes MaterialsTypes { get; set; }
        public virtual PriceUnitList PriceUnitList { get; set; }
        public virtual ProjectsList ProjectsList { get; set; }
        public virtual RSSMaster RSSMaster { get; set; }
        public virtual SampleReceiveList SampleReceiveList1 { get; set; }
        public virtual SampleReceiveList SampleReceiveList2 { get; set; }
        public virtual SampleReceiveList SampleReceiveList11 { get; set; }
        public virtual SampleReceiveList SampleReceiveList3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleReceiveMaterialCustomField> SampleReceiveMaterialCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleReceiveMaterialTableCustomField> SampleReceiveMaterialTableCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleReceiveTestList> SampleReceiveTestList { get; set; }
    }
}
