//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestItems
    {
        public int TestItemsID { get; set; }
        public int FKTestID { get; set; }
        public int FKItemID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string UnitOfMeasure { get; set; }
    
        public virtual ItemsList ItemsList { get; set; }
        public virtual TestsList TestsList { get; set; }
    }
}
