//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestEquipments
    {
        public int TestEquipmentID { get; set; }
        public int FKEquipmentID { get; set; }
        public int FKTestID { get; set; }
    
        public virtual EquipmentsList EquipmentsList { get; set; }
        public virtual TestsList TestsList { get; set; }
    }
}
