//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidityListDetails
    {
        public string Status { get; set; }
        public int ValidityDetailsID { get; set; }
        public int FKValidityID { get; set; }
        public string CertificateName { get; set; }
        public string IDNumber { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Responsible { get; set; }
        public string Remarks { get; set; }
        public string CertificateSerialNumber { get; set; }
        public string CalibratedBy { get; set; }
    
        public virtual ValidityList ValidityList { get; set; }
    }
}
