//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidityList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValidityList()
        {
            this.ValidityListDetails = new HashSet<ValidityListDetails>();
        }
    
        public int ValidityID { get; set; }
        public string ValidityCode { get; set; }
        public string ValidityName { get; set; }
        public int FKLabID { get; set; }
        public bool IsLocked { get; set; }
    
        public virtual LabsList LabsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidityListDetails> ValidityListDetails { get; set; }
    }
}
