//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGelAllInvoice
    {
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> InvoiceEndDate { get; set; }
        public long InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceRefNo { get; set; }
        public Nullable<System.DateTime> InvoiceStartDate { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string ProvideDescription { get; set; }
        public Nullable<decimal> SRTTotal { get; set; }
        public Nullable<decimal> TSTotal { get; set; }
        public string ProjectName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public long JobOrderMasterID { get; set; }
        public string JobOrderNumber { get; set; }
        public bool IsActive { get; set; }
    }
}
