//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewInvoicesBalance
    {
        public long InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceRefNo { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public long FKJobOrderMasterID { get; set; }
        public string ProvideDescription { get; set; }
        public int FKCustomerID { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<decimal> InvoiceBalance { get; set; }
    }
}
