//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSampleReceiveMaterialCustomField
    {
        public int CustomFieldID { get; set; }
        public string CustomFieldName { get; set; }
        public int DataType { get; set; }
        public int FKMaterialTypeID { get; set; }
        public string Value { get; set; }
        public Nullable<long> FkSampleID { get; set; }
        public Nullable<long> SampleReceiveCFLinkID { get; set; }
        public Nullable<int> FkCustomFieldID { get; set; }
    }
}
