//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewWorkOrderList
    {
        public long WorkOrderID { get; set; }
        public string WorkOrderNo { get; set; }
        public Nullable<long> FKJobOrderDetailsID { get; set; }
        public Nullable<long> FKAgreementID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> ShiftStatus { get; set; }
        public Nullable<decimal> RegularWorkHrs { get; set; }
        public Nullable<decimal> RamadanWorkHrs { get; set; }
        public Nullable<decimal> MonthlyRate { get; set; }
        public string UnitOfAddition { get; set; }
        public Nullable<decimal> ExtraWorkHourRate { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> NightShiftPerc { get; set; }
        public Nullable<long> PaySlipID { get; set; }
        public Nullable<long> FKWorkOrderId { get; set; }
        public Nullable<int> NoOfWorkingDays { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> OTRate { get; set; }
        public Nullable<decimal> NormalWorkingHours { get; set; }
        public Nullable<decimal> RamadanWorkingHours { get; set; }
        public Nullable<decimal> OTWorkingHours { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<int> FKCustomerID { get; set; }
        public Nullable<long> JobOrderMasterID { get; set; }
        public string JobOrderNumber { get; set; }
        public Nullable<long> WorkOrderInvoiceId { get; set; }
        public Nullable<long> FkInvoiceId { get; set; }
        public Nullable<long> Expr1 { get; set; }
    }
}
