//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserRolesList
    {
        public int RoleID { get; set; }
        public string RoleAName { get; set; }
        public string RoleEName { get; set; }
        public int UserType { get; set; }
        public Nullable<int> FKModuleID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public int FKLinkID { get; set; }
        public int RoleLinkID { get; set; }
        public string LinksEName { get; set; }
    }
}
