//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewN_OFUnPaidBills
    {
        public long JobOrderMasterID { get; set; }
        public Nullable<int> No_of_PendingPayment { get; set; }
        public Nullable<decimal> TotalPendingAmount { get; set; }
    }
}
