//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQuotationDetails
    {
        public int RowStatus { get; set; }

        public Nullable<decimal> DefaultPrice { get; set; }
        public Nullable<decimal> MinimumPrice { get; set; }
        public long QuotationDetailsID { get; set; }
        public long FKQuotationMasterID { get; set; }
        public int FKTestID { get; set; }
        public int FKPriceUnitID { get; set; }
        public Nullable<long> FKEnquiryDetailsID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FKMaterialTypeID { get; set; }
        public Nullable<int> FKMaterialDetailsID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> UnitType { get; set; }
        public string MaterialsTypesName { get; set; }
        public string MaterialsDetailsName { get; set; }
        public string StandardNumber { get; set; }
        public string TestName { get; set; }
    }
}
