//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNewQuotationMaster
    {
        public string ProjectName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public long QuotationMasterID { get; set; }
        public string QuotationNo { get; set; }
        public bool IsActive { get; set; }
        public int StatusID { get; set; }
    }
}
