//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewJobOrderPendingToInvoicer
    {
        public string ProjectName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public long JobOrderMasterID { get; set; }
        public string JobOrderNumber { get; set; }
        public bool IsActive { get; set; }
    }
}
