//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRSS
    {
        public string ContractorName { get; set; }
        public string ProjectName { get; set; }
        public long JobOrderMasterID { get; set; }
        public long RSSMasterId { get; set; }
        public long FKJobOrderMasterID { get; set; }
        public string RSSNumber { get; set; }
        public System.DateTime RSSDate { get; set; }
        public string ContactPersonAtSite { get; set; }
        public string ContactMobile { get; set; }
        public string SiteLocation { get; set; }
        public Nullable<int> FkEmpId { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsSampled { get; set; }
        public string SampleNo { get; set; }
    }
}
