//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTestUnits
    {
        public int TestID { get; set; }
        public string StandardNumber { get; set; }
        public string AshghalTestNumber { get; set; }
        public string TestName { get; set; }
        public string TestDescription { get; set; }
        public string ShortName { get; set; }
        public int FKPriceUnitID { get; set; }
        public int FKAccreditionID { get; set; }
    }
}
