//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderInvoice
    {
        public long WorkOrderInvoiceId { get; set; }
        public long FkInvoiceId { get; set; }
        public long FkWorkOrderId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual WorkOrderList WorkOrderList { get; set; }
    }
}
