//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderList
    {
        public long FKJobOrderMasterID { get; set; }
        public int RowStatus { get; set; }
        public decimal? DueAmount { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsChecked { get; set; }
        public bool IsApproved { get; set; }
        public bool IsInvoiced { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrderList()
        {
            this.TimesheetPaySlip = new HashSet<TimesheetPaySlip>();
            this.WorkOrderInvoice = new HashSet<WorkOrderInvoice>();
            this.WorkOrderTimeSheet = new HashSet<WorkOrderTimeSheet>();
        }
    
        public long WorkOrderID { get; set; }
        public string WorkOrderNo { get; set; }
        public Nullable<long> FKJobOrderDetailsID { get; set; }
        public Nullable<long> FKAgreementID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> ShiftStatus { get; set; }
        public Nullable<decimal> RegularWorkHrs { get; set; }
        public Nullable<decimal> RamadanWorkHrs { get; set; }
        public Nullable<decimal> MonthlyRate { get; set; }
        public string UnitOfAddition { get; set; }
        public Nullable<decimal> ExtraWorkHourRate { get; set; }
        public Nullable<decimal> NightShiftPerc { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Description { get; set; }
    
        public virtual JobOrderDetails JobOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetPaySlip> TimesheetPaySlip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderInvoice> WorkOrderInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderTimeSheet> WorkOrderTimeSheet { get; set; }
    }
}
