using DevExpress.DataAccess;
using DevExpress.DataAccess.Sql;
using DevExpress.Utils;
using DevExpress.XtraPrinting;
using DevExpress.XtraReports.Parameters;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Printing;
using System.Resources;

namespace PioneerLab.Reports
{
	public class Invoice : XtraReport
	{
		private IContainer components;

		private DetailBand Detail;

		private TopMarginBand TopMargin;

		private BottomMarginBand BottomMargin;

		private XRTable xrTable1;

		private XRTableRow xrTableRow1;

		private XRTableCell xrTableCell1;

		private XRTableRow xrTableRow2;

		private XRTableCell xrTableCell2;

		private XRLabel xrLabel1;

		private XRLabel xrLabel6;

		private XRLabel xrLabel8;

		private XRLabel xrLabel22;

		private XRLabel xrLabel20;

		private SqlDataSource sqlDataSource1;

		private PageFooterBand pageFooterBand1;

		private ReportHeaderBand reportHeaderBand1;

		private XRControlStyle Title;

		private XRControlStyle FieldCaption;

		private XRControlStyle PageInfo;

		private XRControlStyle DataField;

		private DetailReportBand DetailReport;

		private DetailBand Detail1;

		private XRTable xrTable3;

		private XRTableRow xrTableRow5;

		private XRTableCell xrTableCell9;

		private XRTableCell xrTableCell10;

		private XRTableCell xrTableCell11;

		private XRTableCell xrTableCell12;

		private XRTableCell xrTableCell13;

		private GroupHeaderBand GroupHeader1;

		private XRTable xrTable4;

		private XRTableRow xrTableRow6;

		private XRTableCell xrTableCell14;

		private XRTableCell xrTableCell15;

		private XRTableCell xrTableCell16;

		private XRTableCell xrTableCell17;

		private XRTableCell xrTableCell18;

		private DetailReportBand DetailReport2;

		private DetailBand Detail3;

		private XRLabel xrLabel3;

		private XRLabel xrLabel5;

		private XRLabel xrLabel15;

		private XRLabel xrLabel16;

		private XRLabel xrLabel17;

		private XRLabel xrLabel18;

		private DetailReportBand DetailReport1;

		private DetailBand Detail2;

		private XRLabel xrLabel21;

		private XRLabel xrLabel19;

		private Parameter InvoiceID;

		private XRTableCell xrTableCell4;

		private XRTableCell xrTableCell3;

		private XRTable xrTable2;

		private XRTableRow xrTableRow3;

		private XRTableCell xrTableCell5;

		private XRTableCell xrTableCell6;

		private XRTableCell xrTableCell7;

		private XRTableCell xrTableCell8;

		private XRTableCell xrTableCell19;

		private XRTableCell xrTableCell20;

		private CalculatedField JONumber;

		private CalculatedField WONumber;

		private XRTableRow xrTableRow4;

		private XRTableCell xrTableCell21;

		private XRTableRow xrTableRow7;

		private XRTableCell xrTableCell22;

		private XRTableRow xrTableRow9;

		private XRTableCell xrTableCell24;

		private XRTableRow xrTableRow8;

		private XRTableCell xrTableCell23;

		private XRLabel xrLabel2;

		private XRLabel xrLabel9;

		private XRLabel xrLabel11;

		private XRLabel xrLabel10;

		private XRLabel xrLabel7;

		private XRLabel xrLabel4;

		public Invoice()
		{
			this.InitializeComponent();
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			SelectQuery selectQuery = new SelectQuery();
			Column column = new Column();
			ColumnExpression columnExpression = new ColumnExpression();
			Table table = new Table();
			Column column1 = new Column();
			ColumnExpression columnExpression1 = new ColumnExpression();
			Column column2 = new Column();
			ColumnExpression columnExpression2 = new ColumnExpression();
			Column column3 = new Column();
			ColumnExpression columnExpression3 = new ColumnExpression();
			Column column4 = new Column();
			ColumnExpression columnExpression4 = new ColumnExpression();
			Column column5 = new Column();
			ColumnExpression columnExpression5 = new ColumnExpression();
			Column column6 = new Column();
			ColumnExpression columnExpression6 = new ColumnExpression();
			Column column7 = new Column();
			ColumnExpression columnExpression7 = new ColumnExpression();
			Column column8 = new Column();
			ColumnExpression columnExpression8 = new ColumnExpression();
			Column column9 = new Column();
			ColumnExpression columnExpression9 = new ColumnExpression();
			Column column10 = new Column();
			ColumnExpression columnExpression10 = new ColumnExpression();
			Column column11 = new Column();
			ColumnExpression columnExpression11 = new ColumnExpression();
			Table table1 = new Table();
			Column column12 = new Column();
			ColumnExpression columnExpression12 = new ColumnExpression();
			Table table2 = new Table();
			Column column13 = new Column();
			ColumnExpression columnExpression13 = new ColumnExpression();
			Column column14 = new Column();
			ColumnExpression columnExpression14 = new ColumnExpression();
			Column column15 = new Column();
			ColumnExpression columnExpression15 = new ColumnExpression();
			Column column16 = new Column();
			ColumnExpression columnExpression16 = new ColumnExpression();
			Column column17 = new Column();
			ColumnExpression columnExpression17 = new ColumnExpression();
			Table table3 = new Table();
			Join join = new Join();
			RelationColumnInfo relationColumnInfo = new RelationColumnInfo();
			Join join1 = new Join();
			RelationColumnInfo relationColumnInfo1 = new RelationColumnInfo();
			Join join2 = new Join();
			RelationColumnInfo relationColumnInfo2 = new RelationColumnInfo();
			Join join3 = new Join();
			RelationColumnInfo relationColumnInfo3 = new RelationColumnInfo();
			CustomSqlQuery customSqlQuery = new CustomSqlQuery();
			ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(Invoice));
			CustomSqlQuery str = new CustomSqlQuery();
			MasterDetailInfo masterDetailInfo = new MasterDetailInfo();
			RelationColumnInfo relationColumnInfo4 = new RelationColumnInfo();
			MasterDetailInfo masterDetailInfo1 = new MasterDetailInfo();
			RelationColumnInfo relationColumnInfo5 = new RelationColumnInfo();
			DynamicListLookUpSettings dynamicListLookUpSetting = new DynamicListLookUpSettings();
			this.sqlDataSource1 = new SqlDataSource(this.components);
			this.Detail = new DetailBand();
			this.xrTable1 = new XRTable();
			this.xrTableRow1 = new XRTableRow();
			this.xrTableCell1 = new XRTableCell();
			this.xrTableRow2 = new XRTableRow();
			this.xrTableCell2 = new XRTableCell();
			this.xrTableRow4 = new XRTableRow();
			this.xrTableCell21 = new XRTableCell();
			this.xrTableRow7 = new XRTableRow();
			this.xrTableCell22 = new XRTableCell();
			this.xrTableRow9 = new XRTableRow();
			this.xrTableCell24 = new XRTableCell();
			this.xrTableRow8 = new XRTableRow();
			this.xrTableCell23 = new XRTableCell();
			this.xrLabel3 = new XRLabel();
			this.xrLabel5 = new XRLabel();
			this.xrLabel15 = new XRLabel();
			this.xrLabel16 = new XRLabel();
			this.xrLabel17 = new XRLabel();
			this.xrLabel18 = new XRLabel();
			this.TopMargin = new TopMarginBand();
			this.xrLabel2 = new XRLabel();
			this.xrLabel9 = new XRLabel();
			this.xrLabel1 = new XRLabel();
			this.xrLabel6 = new XRLabel();
			this.xrLabel8 = new XRLabel();
			this.xrLabel22 = new XRLabel();
			this.xrLabel20 = new XRLabel();
			this.BottomMargin = new BottomMarginBand();
			this.pageFooterBand1 = new PageFooterBand();
			this.reportHeaderBand1 = new ReportHeaderBand();
			this.Title = new XRControlStyle();
			this.FieldCaption = new XRControlStyle();
			this.PageInfo = new XRControlStyle();
			this.DataField = new XRControlStyle();
			this.DetailReport = new DetailReportBand();
			this.Detail1 = new DetailBand();
			this.xrTable3 = new XRTable();
			this.xrTableRow5 = new XRTableRow();
			this.xrTableCell4 = new XRTableCell();
			this.xrTableCell9 = new XRTableCell();
			this.xrTableCell10 = new XRTableCell();
			this.xrTableCell11 = new XRTableCell();
			this.xrTableCell12 = new XRTableCell();
			this.xrTableCell13 = new XRTableCell();
			this.GroupHeader1 = new GroupHeaderBand();
			this.xrTable4 = new XRTable();
			this.xrTableRow6 = new XRTableRow();
			this.xrTableCell3 = new XRTableCell();
			this.xrTableCell14 = new XRTableCell();
			this.xrTableCell15 = new XRTableCell();
			this.xrTableCell16 = new XRTableCell();
			this.xrTableCell17 = new XRTableCell();
			this.xrTableCell18 = new XRTableCell();
			this.DetailReport2 = new DetailReportBand();
			this.Detail3 = new DetailBand();
			this.xrTable2 = new XRTable();
			this.xrTableRow3 = new XRTableRow();
			this.xrTableCell5 = new XRTableCell();
			this.xrTableCell6 = new XRTableCell();
			this.xrTableCell7 = new XRTableCell();
			this.xrTableCell8 = new XRTableCell();
			this.xrTableCell19 = new XRTableCell();
			this.xrTableCell20 = new XRTableCell();
			this.DetailReport1 = new DetailReportBand();
			this.Detail2 = new DetailBand();
			this.xrLabel21 = new XRLabel();
			this.xrLabel19 = new XRLabel();
			this.InvoiceID = new Parameter();
			this.JONumber = new CalculatedField();
			this.WONumber = new CalculatedField();
			this.xrLabel4 = new XRLabel();
			this.xrLabel7 = new XRLabel();
			this.xrLabel10 = new XRLabel();
			this.xrLabel11 = new XRLabel();
			((ISupportInitialize)this.xrTable1).BeginInit();
			((ISupportInitialize)this.xrTable3).BeginInit();
			((ISupportInitialize)this.xrTable4).BeginInit();
			((ISupportInitialize)this.xrTable2).BeginInit();
			((ISupportInitialize)this).BeginInit();
			this.sqlDataSource1.ConnectionName = "localhost_LabSys_Connection";
			this.sqlDataSource1.Name = "sqlDataSource1";
			columnExpression.ColumnName = "InvoiceId";
			table.MetaSerializable = "30|30|125|300";
			table.Name = "Invoice";
			columnExpression.Table = table;
			column.Expression = columnExpression;
			columnExpression1.ColumnName = "InvoiceNumber";
			columnExpression1.Table = table;
			column1.Expression = columnExpression1;
			columnExpression2.ColumnName = "InvoiceDate";
			columnExpression2.Table = table;
			column2.Expression = columnExpression2;
			columnExpression3.ColumnName = "InvoiceRefNo";
			columnExpression3.Table = table;
			column3.Expression = columnExpression3;
			columnExpression4.ColumnName = "FKJobOrderMasterID";
			columnExpression4.Table = table;
			column4.Expression = columnExpression4;
			columnExpression5.ColumnName = "SRTTotal";
			columnExpression5.Table = table;
			column5.Expression = columnExpression5;
			columnExpression6.ColumnName = "TSTotal";
			columnExpression6.Table = table;
			column6.Expression = columnExpression6;
			columnExpression7.ColumnName = "InvoiceTotal";
			columnExpression7.Table = table;
			column7.Expression = columnExpression7;
			columnExpression8.ColumnName = "Disount";
			columnExpression8.Table = table;
			column8.Expression = columnExpression8;
			columnExpression9.ColumnName = "NetAmount";
			columnExpression9.Table = table;
			column9.Expression = columnExpression9;
			columnExpression10.ColumnName = "ProvideDescription";
			columnExpression10.Table = table;
			column10.Expression = columnExpression10;
			columnExpression11.ColumnName = "CustomerName";
			table1.MetaSerializable = "340|30|125|300";
			table1.Name = "CustomersList";
			columnExpression11.Table = table1;
			column11.Expression = columnExpression11;
			columnExpression12.ColumnName = "PaymentTerms";
			table2.MetaSerializable = "495|30|125|360";
			table2.Name = "QuotationMaster";
			columnExpression12.Table = table2;
			column12.Expression = columnExpression12;
			columnExpression13.ColumnName = "PhoneNumber";
			columnExpression13.Table = table1;
			column13.Expression = columnExpression13;
			columnExpression14.ColumnName = "FaxNumber";
			columnExpression14.Table = table1;
			column14.Expression = columnExpression14;
			columnExpression15.ColumnName = "Email";
			columnExpression15.Table = table1;
			column15.Expression = columnExpression15;
			columnExpression16.ColumnName = "Address";
			columnExpression16.Table = table1;
			column16.Expression = columnExpression16;
			columnExpression17.ColumnName = "JobOrderNumber";
			table3.MetaSerializable = "185|30|125|360";
			table3.Name = "JobOrderMaster";
			columnExpression17.Table = table3;
			column17.Expression = columnExpression17;
			selectQuery.Columns.Add(column);
			selectQuery.Columns.Add(column1);
			selectQuery.Columns.Add(column2);
			selectQuery.Columns.Add(column3);
			selectQuery.Columns.Add(column4);
			selectQuery.Columns.Add(column5);
			selectQuery.Columns.Add(column6);
			selectQuery.Columns.Add(column7);
			selectQuery.Columns.Add(column8);
			selectQuery.Columns.Add(column9);
			selectQuery.Columns.Add(column10);
			selectQuery.Columns.Add(column11);
			selectQuery.Columns.Add(column12);
			selectQuery.Columns.Add(column13);
			selectQuery.Columns.Add(column14);
			selectQuery.Columns.Add(column15);
			selectQuery.Columns.Add(column16);
			selectQuery.Columns.Add(column17);
			selectQuery.Name = "Invoice";
			relationColumnInfo.NestedKeyColumn = "JobOrderMasterID";
			relationColumnInfo.ParentKeyColumn = "FKJobOrderMasterID";
			join.KeyColumns.Add(relationColumnInfo);
			join.Nested = table3;
			join.Parent = table;
			relationColumnInfo1.NestedKeyColumn = "CustomerID";
			relationColumnInfo1.ParentKeyColumn = "FKCustomerID";
			join1.KeyColumns.Add(relationColumnInfo1);
			join1.Nested = table1;
			join1.Parent = table3;
			relationColumnInfo2.NestedKeyColumn = "FKCustomerID";
			relationColumnInfo2.ParentKeyColumn = "CustomerID";
			join2.KeyColumns.Add(relationColumnInfo2);
			join2.Nested = table2;
			join2.Parent = table1;
			relationColumnInfo3.NestedKeyColumn = "QuotationMasterID";
			relationColumnInfo3.ParentKeyColumn = "FKQuotationMasterID";
			join3.KeyColumns.Add(relationColumnInfo3);
			join3.Nested = table2;
			join3.Parent = table3;
			selectQuery.Relations.Add(join);
			selectQuery.Relations.Add(join1);
			selectQuery.Relations.Add(join2);
			selectQuery.Relations.Add(join3);
			selectQuery.Tables.Add(table);
			selectQuery.Tables.Add(table3);
			selectQuery.Tables.Add(table1);
			selectQuery.Tables.Add(table2);
			customSqlQuery.Name = "SampleReceiveTestInvoice";
			customSqlQuery.Sql = componentResourceManager.GetString("customSqlQuery1.Sql");
			str.Name = "WorkOrderList";
			str.Sql = componentResourceManager.GetString("customSqlQuery2.Sql");
			this.sqlDataSource1.Queries.AddRange(new SqlQuery[] { selectQuery, customSqlQuery, str });
			masterDetailInfo.DetailQueryName = "SampleReceiveTestInvoice";
			relationColumnInfo4.NestedKeyColumn = "InvoiceId";
			relationColumnInfo4.ParentKeyColumn = "InvoiceId";
			masterDetailInfo.KeyColumns.Add(relationColumnInfo4);
			masterDetailInfo.MasterQueryName = "Invoice";
			masterDetailInfo1.DetailQueryName = "WorkOrderList";
			relationColumnInfo5.NestedKeyColumn = "InvoiceId";
			relationColumnInfo5.ParentKeyColumn = "InvoiceId";
			masterDetailInfo1.KeyColumns.Add(relationColumnInfo5);
			masterDetailInfo1.MasterQueryName = "Invoice";
			this.sqlDataSource1.Relations.AddRange(new MasterDetailInfo[] { masterDetailInfo, masterDetailInfo1 });
			this.sqlDataSource1.ResultSchemaSerializable = componentResourceManager.GetString("sqlDataSource1.ResultSchemaSerializable");
			XRControlCollection controls = this.Detail.Controls;
			XRControl[] xRControlArrays = new XRControl[] { this.xrTable1, this.xrLabel3, this.xrLabel5, this.xrLabel15, this.xrLabel16, this.xrLabel17, this.xrLabel18 };
			controls.AddRange(xRControlArrays);
			this.Detail.Dpi = 100f;
			this.Detail.HeightF = 196.0834f;
			this.Detail.KeepTogether = true;
			this.Detail.KeepTogetherWithDetailReports = true;
			this.Detail.Name = "Detail";
			this.Detail.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.Detail.PageBreak = DevExpress.XtraReports.UI.PageBreak.BeforeBand;
			this.Detail.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrTable1.Borders = BorderSide.All;
			this.xrTable1.Dpi = 100f;
			this.xrTable1.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrTable1.LocationFloat = new PointFloat(30.55554f, 11.4584f);
			this.xrTable1.Name = "xrTable1";
			this.xrTable1.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection rows = this.xrTable1.Rows;
			XRTableRow[] xRTableRowArray = new XRTableRow[] { this.xrTableRow1, this.xrTableRow2, this.xrTableRow4, this.xrTableRow7, this.xrTableRow9, this.xrTableRow8 };
			rows.AddRange(xRTableRowArray);
			this.xrTable1.SizeF = new System.Drawing.SizeF(440.625f, 130.9634f);
			this.xrTable1.StylePriority.UseBorders = false;
			this.xrTable1.StylePriority.UseFont = false;
			this.xrTable1.StylePriority.UsePadding = false;
			XRTableCellCollection cells = this.xrTableRow1.Cells;
			XRTableCell[] xRTableCellArray = new XRTableCell[] { this.xrTableCell1 };
			cells.AddRange(xRTableCellArray);
			this.xrTableRow1.Dpi = 100f;
			this.xrTableRow1.Name = "xrTableRow1";
			this.xrTableRow1.Weight = 2.23003423591481;
			this.xrTableCell1.BackColor = Color.Gainsboro;
			this.xrTableCell1.Dpi = 100f;
			this.xrTableCell1.Name = "xrTableCell1";
			this.xrTableCell1.StylePriority.UseBackColor = false;
			this.xrTableCell1.Text = "Bill To:";
			this.xrTableCell1.Weight = 1;
			XRTableCellCollection xRTableCellCollections = this.xrTableRow2.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell2 };
			xRTableCellCollections.AddRange(xRTableCellArray);
			this.xrTableRow2.Dpi = 100f;
			this.xrTableRow2.Name = "xrTableRow2";
			this.xrTableRow2.Weight = 2.31163263420237;
			this.xrTableCell2.Borders = BorderSide.Left | BorderSide.Right;
			XRBindingCollection dataBindings = this.xrTableCell2.DataBindings;
			XRBinding[] xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.CustomerName") };
			dataBindings.AddRange(xRBinding);
			this.xrTableCell2.Dpi = 100f;
			this.xrTableCell2.Name = "xrTableCell2";
			this.xrTableCell2.StylePriority.UseBorders = false;
			this.xrTableCell2.Weight = 1;
			XRTableCellCollection cells1 = this.xrTableRow4.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell21 };
			cells1.AddRange(xRTableCellArray);
			this.xrTableRow4.Dpi = 100f;
			this.xrTableRow4.Name = "xrTableRow4";
			this.xrTableRow4.Weight = 2.31163263420237;
			this.xrTableCell21.Borders = BorderSide.Left | BorderSide.Right;
			XRBindingCollection xRBindingCollections = this.xrTableCell21.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.Address") };
			xRBindingCollections.AddRange(xRBinding);
			this.xrTableCell21.Dpi = 100f;
			this.xrTableCell21.Name = "xrTableCell21";
			this.xrTableCell21.StylePriority.UseBorders = false;
			this.xrTableCell21.Weight = 1;
			XRTableCellCollection xRTableCellCollections1 = this.xrTableRow7.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell22 };
			xRTableCellCollections1.AddRange(xRTableCellArray);
			this.xrTableRow7.Dpi = 100f;
			this.xrTableRow7.Name = "xrTableRow7";
			this.xrTableRow7.Weight = 2.31163263420237;
			this.xrTableCell22.Borders = BorderSide.Left | BorderSide.Right;
			XRBindingCollection dataBindings1 = this.xrTableCell22.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.Email") };
			dataBindings1.AddRange(xRBinding);
			this.xrTableCell22.Dpi = 100f;
			this.xrTableCell22.Name = "xrTableCell22";
			this.xrTableCell22.StylePriority.UseBorders = false;
			this.xrTableCell22.Weight = 1;
			XRTableCellCollection cells2 = this.xrTableRow9.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell24 };
			cells2.AddRange(xRTableCellArray);
			this.xrTableRow9.Dpi = 100f;
			this.xrTableRow9.Name = "xrTableRow9";
			this.xrTableRow9.Weight = 2.31163263420237;
			this.xrTableCell24.Borders = BorderSide.Left | BorderSide.Right;
			XRBindingCollection xRBindingCollections1 = this.xrTableCell24.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.PhoneNumber") };
			xRBindingCollections1.AddRange(xRBinding);
			this.xrTableCell24.Dpi = 100f;
			this.xrTableCell24.Name = "xrTableCell24";
			this.xrTableCell24.StylePriority.UseBorders = false;
			this.xrTableCell24.Weight = 1;
			XRTableCellCollection xRTableCellCollections2 = this.xrTableRow8.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell23 };
			xRTableCellCollections2.AddRange(xRTableCellArray);
			this.xrTableRow8.Dpi = 100f;
			this.xrTableRow8.Name = "xrTableRow8";
			this.xrTableRow8.Weight = 2.31163263420237;
			this.xrTableCell23.Borders = BorderSide.Left | BorderSide.Right | BorderSide.Bottom;
			XRBindingCollection dataBindings2 = this.xrTableCell23.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.FaxNumber") };
			dataBindings2.AddRange(xRBinding);
			this.xrTableCell23.Dpi = 100f;
			this.xrTableCell23.Name = "xrTableCell23";
			this.xrTableCell23.StylePriority.UseBorders = false;
			this.xrTableCell23.Weight = 1;
			this.xrLabel3.BackColor = Color.Gainsboro;
			this.xrLabel3.Borders = BorderSide.All;
			this.xrLabel3.Dpi = 100f;
			this.xrLabel3.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrLabel3.LocationFloat = new PointFloat(29.505f, 154.7916f);
			this.xrLabel3.Name = "xrLabel3";
			this.xrLabel3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel3.SizeF = new System.Drawing.SizeF(259.1894f, 20.64583f);
			this.xrLabel3.StylePriority.UseBackColor = false;
			this.xrLabel3.StylePriority.UseBorders = false;
			this.xrLabel3.StylePriority.UseFont = false;
			this.xrLabel3.StylePriority.UsePadding = false;
			this.xrLabel3.StylePriority.UseTextAlignment = false;
			this.xrLabel3.Text = "Customer ID";
			this.xrLabel3.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrLabel5.BackColor = Color.Gainsboro;
			this.xrLabel5.Borders = BorderSide.Top | BorderSide.Right | BorderSide.Bottom;
			this.xrLabel5.Dpi = 100f;
			this.xrLabel5.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrLabel5.LocationFloat = new PointFloat(288.8194f, 154.7916f);
			this.xrLabel5.Name = "xrLabel5";
			this.xrLabel5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel5.SizeF = new System.Drawing.SizeF(257.5545f, 20.64583f);
			this.xrLabel5.StylePriority.UseBackColor = false;
			this.xrLabel5.StylePriority.UseBorders = false;
			this.xrLabel5.StylePriority.UseFont = false;
			this.xrLabel5.StylePriority.UsePadding = false;
			this.xrLabel5.StylePriority.UseTextAlignment = false;
			this.xrLabel5.Text = "Customer PO";
			this.xrLabel5.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrLabel15.BackColor = Color.Gainsboro;
			this.xrLabel15.Borders = BorderSide.Top | BorderSide.Right | BorderSide.Bottom;
			this.xrLabel15.Dpi = 100f;
			this.xrLabel15.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrLabel15.LocationFloat = new PointFloat(546.4989f, 154.7918f);
			this.xrLabel15.Name = "xrLabel15";
			this.xrLabel15.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel15.SizeF = new System.Drawing.SizeF(278.1797f, 20.64584f);
			this.xrLabel15.StylePriority.UseBackColor = false;
			this.xrLabel15.StylePriority.UseBorders = false;
			this.xrLabel15.StylePriority.UseFont = false;
			this.xrLabel15.StylePriority.UsePadding = false;
			this.xrLabel15.StylePriority.UseTextAlignment = false;
			this.xrLabel15.Text = "Payment Terms";
			this.xrLabel15.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrLabel16.Borders = BorderSide.Left | BorderSide.Right | BorderSide.Bottom;
			XRBindingCollection xRBindingCollections2 = this.xrLabel16.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.CustomerName") };
			xRBindingCollections2.AddRange(xRBinding);
			this.xrLabel16.Dpi = 100f;
			this.xrLabel16.LocationFloat = new PointFloat(29.37842f, 175.4375f);
			this.xrLabel16.Name = "xrLabel16";
			this.xrLabel16.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel16.SizeF = new System.Drawing.SizeF(259.4409f, 20.64583f);
			this.xrLabel16.StylePriority.UseBorders = false;
			this.xrLabel16.StylePriority.UsePadding = false;
			this.xrLabel16.StylePriority.UseTextAlignment = false;
			this.xrLabel16.Text = "xrLabel16";
			this.xrLabel16.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrLabel17.Borders = BorderSide.Right | BorderSide.Bottom;
			this.xrLabel17.Dpi = 100f;
			this.xrLabel17.LocationFloat = new PointFloat(288.9444f, 175.4375f);
			this.xrLabel17.Name = "xrLabel17";
			this.xrLabel17.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel17.SizeF = new System.Drawing.SizeF(257.4295f, 20.64583f);
			this.xrLabel17.StylePriority.UseBorders = false;
			this.xrLabel17.StylePriority.UsePadding = false;
			this.xrLabel17.StylePriority.UseTextAlignment = false;
			this.xrLabel17.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrLabel18.Borders = BorderSide.Right | BorderSide.Bottom;
			XRBindingCollection dataBindings3 = this.xrLabel18.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.PaymentTerms") };
			dataBindings3.AddRange(xRBinding);
			this.xrLabel18.Dpi = 100f;
			this.xrLabel18.LocationFloat = new PointFloat(546.4989f, 175.4375f);
			this.xrLabel18.Name = "xrLabel18";
			this.xrLabel18.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel18.SizeF = new System.Drawing.SizeF(278.3888f, 20.64584f);
			this.xrLabel18.StylePriority.UseBorders = false;
			this.xrLabel18.StylePriority.UsePadding = false;
			this.xrLabel18.StylePriority.UseTextAlignment = false;
			this.xrLabel18.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			XRControlCollection xRControlCollection = this.TopMargin.Controls;
			xRControlArrays = new XRControl[] { this.xrLabel2, this.xrLabel9, this.xrLabel1, this.xrLabel6, this.xrLabel8, this.xrLabel22, this.xrLabel20 };
			xRControlCollection.AddRange(xRControlArrays);
			this.TopMargin.Dpi = 100f;
			this.TopMargin.Font = new System.Drawing.Font("Traditional Arabic", 9.75f);
			this.TopMargin.HeightF = 109.5833f;
			this.TopMargin.Name = "TopMargin";
			this.TopMargin.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.TopMargin.StylePriority.UseFont = false;
			this.TopMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRBindingCollection xRBindingCollections3 = this.xrLabel2.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.JobOrderNumber", "{0:dd MMM yyyy}") };
			xRBindingCollections3.AddRange(xRBinding);
			this.xrLabel2.Dpi = 100f;
			this.xrLabel2.LocationFloat = new PointFloat(650.2617f, 88.33334f);
			this.xrLabel2.Name = "xrLabel2";
			this.xrLabel2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel2.SizeF = new System.Drawing.SizeF(147.2084f, 18f);
			this.xrLabel2.StyleName = "DataField";
			this.xrLabel9.Dpi = 100f;
			this.xrLabel9.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel9.LocationFloat = new PointFloat(536.5832f, 88.33334f);
			this.xrLabel9.Name = "xrLabel9";
			this.xrLabel9.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel9.SizeF = new System.Drawing.SizeF(113.6785f, 18f);
			this.xrLabel9.StyleName = "FieldCaption";
			this.xrLabel9.StylePriority.UseForeColor = false;
			this.xrLabel9.Text = "Job Order No:";
			this.xrLabel1.Dpi = 100f;
			this.xrLabel1.Font = new System.Drawing.Font("Arial", 36f, FontStyle.Bold | FontStyle.Italic | FontStyle.Underline);
			this.xrLabel1.ForeColor = Color.FromArgb(126, 126, 126);
			this.xrLabel1.LocationFloat = new PointFloat(269.5137f, 28.00001f);
			this.xrLabel1.Name = "xrLabel1";
			this.xrLabel1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel1.SizeF = new System.Drawing.SizeF(237.2084f, 61.74999f);
			this.xrLabel1.StyleName = "FieldCaption";
			this.xrLabel1.StylePriority.UseFont = false;
			this.xrLabel1.StylePriority.UseForeColor = false;
			this.xrLabel1.Text = "INVOICE";
			this.xrLabel6.Dpi = 100f;
			this.xrLabel6.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel6.LocationFloat = new PointFloat(536.4582f, 65.33334f);
			this.xrLabel6.Name = "xrLabel6";
			this.xrLabel6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel6.SizeF = new System.Drawing.SizeF(94.29169f, 18f);
			this.xrLabel6.StyleName = "FieldCaption";
			this.xrLabel6.StylePriority.UseForeColor = false;
			this.xrLabel6.Text = "Invoice Date:";
			this.xrLabel8.Dpi = 100f;
			this.xrLabel8.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel8.LocationFloat = new PointFloat(536.4582f, 41.54167f);
			this.xrLabel8.Name = "xrLabel8";
			this.xrLabel8.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel8.SizeF = new System.Drawing.SizeF(116.8333f, 18f);
			this.xrLabel8.StyleName = "FieldCaption";
			this.xrLabel8.StylePriority.UseForeColor = false;
			this.xrLabel8.Text = "Invoice Number:";
			XRBindingCollection dataBindings4 = this.xrLabel22.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.InvoiceNumber") };
			dataBindings4.AddRange(xRBinding);
			this.xrLabel22.Dpi = 100f;
			this.xrLabel22.LocationFloat = new PointFloat(653.2915f, 41.54167f);
			this.xrLabel22.Name = "xrLabel22";
			this.xrLabel22.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel22.SizeF = new System.Drawing.SizeF(108.5f, 18f);
			this.xrLabel22.StyleName = "DataField";
			this.xrLabel22.Text = "xrLabel22";
			XRBindingCollection xRBindingCollections4 = this.xrLabel20.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.InvoiceDate", "{0:dd MMM yyyy}") };
			xRBindingCollections4.AddRange(xRBinding);
			this.xrLabel20.Dpi = 100f;
			this.xrLabel20.LocationFloat = new PointFloat(650.2618f, 65.33334f);
			this.xrLabel20.Name = "xrLabel20";
			this.xrLabel20.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel20.SizeF = new System.Drawing.SizeF(147.2084f, 18f);
			this.xrLabel20.StyleName = "DataField";
			this.xrLabel20.Text = "xrLabel20";
			XRControlCollection controls1 = this.BottomMargin.Controls;
			xRControlArrays = new XRControl[] { this.xrLabel11, this.xrLabel10, this.xrLabel7, this.xrLabel4 };
			controls1.AddRange(xRControlArrays);
			this.BottomMargin.Dpi = 100f;
			this.BottomMargin.HeightF = 72.91666f;
			this.BottomMargin.Name = "BottomMargin";
			this.BottomMargin.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.BottomMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.pageFooterBand1.Dpi = 100f;
			this.pageFooterBand1.HeightF = 0f;
			this.pageFooterBand1.Name = "pageFooterBand1";
			this.reportHeaderBand1.Dpi = 100f;
			this.reportHeaderBand1.HeightF = 3.083324f;
			this.reportHeaderBand1.Name = "reportHeaderBand1";
			this.Title.BackColor = Color.Transparent;
			this.Title.BorderColor = Color.Black;
			this.Title.Borders = BorderSide.None;
			this.Title.BorderWidth = 1f;
			this.Title.Font = new System.Drawing.Font("Times New Roman", 20f, FontStyle.Bold);
			this.Title.ForeColor = Color.Maroon;
			this.Title.Name = "Title";
			this.FieldCaption.BackColor = Color.Transparent;
			this.FieldCaption.BorderColor = Color.Black;
			this.FieldCaption.Borders = BorderSide.None;
			this.FieldCaption.BorderWidth = 1f;
			this.FieldCaption.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Bold);
			this.FieldCaption.ForeColor = Color.Maroon;
			this.FieldCaption.Name = "FieldCaption";
			this.PageInfo.BackColor = Color.Transparent;
			this.PageInfo.BorderColor = Color.Black;
			this.PageInfo.Borders = BorderSide.None;
			this.PageInfo.BorderWidth = 1f;
			this.PageInfo.Font = new System.Drawing.Font("Times New Roman", 10f, FontStyle.Bold);
			this.PageInfo.ForeColor = Color.Black;
			this.PageInfo.Name = "PageInfo";
			this.DataField.BackColor = Color.Transparent;
			this.DataField.BorderColor = Color.Black;
			this.DataField.Borders = BorderSide.None;
			this.DataField.BorderWidth = 1f;
			this.DataField.Font = new System.Drawing.Font("Times New Roman", 10f);
			this.DataField.ForeColor = Color.Black;
			this.DataField.Name = "DataField";
			this.DataField.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			BandCollection bands = this.DetailReport.Bands;
			DevExpress.XtraReports.UI.Band[] detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail1, this.GroupHeader1 };
			bands.AddRange(detail1);
			this.DetailReport.DataMember = "Invoice.InvoiceSampleReceiveTestInvoice";
			this.DetailReport.DataSource = this.sqlDataSource1;
			this.DetailReport.Dpi = 100f;
			this.DetailReport.Level = 0;
			this.DetailReport.Name = "DetailReport";
			XRControlCollection xRControlCollection1 = this.Detail1.Controls;
			xRControlArrays = new XRControl[] { this.xrTable3 };
			xRControlCollection1.AddRange(xRControlArrays);
			this.Detail1.Dpi = 100f;
			this.Detail1.HeightF = 25f;
			this.Detail1.Name = "Detail1";
			this.xrTable3.Borders = BorderSide.Left | BorderSide.Right | BorderSide.Bottom;
			this.xrTable3.Dpi = 100f;
			this.xrTable3.LocationFloat = new PointFloat(29.37842f, 0f);
			this.xrTable3.Name = "xrTable3";
			this.xrTable3.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection xRTableRowCollections = this.xrTable3.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow5 };
			xRTableRowCollections.AddRange(xRTableRowArray);
			this.xrTable3.SizeF = new System.Drawing.SizeF(794.8868f, 25f);
			this.xrTable3.StylePriority.UseBorders = false;
			this.xrTable3.StylePriority.UsePadding = false;
			XRTableCellCollection cells3 = this.xrTableRow5.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell4, this.xrTableCell9, this.xrTableCell10, this.xrTableCell11, this.xrTableCell12, this.xrTableCell13 };
			cells3.AddRange(xRTableCellArray);
			this.xrTableRow5.Dpi = 100f;
			this.xrTableRow5.Name = "xrTableRow5";
			this.xrTableRow5.Weight = 11.5;
			this.xrTableCell4.Dpi = 100f;
			this.xrTableCell4.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrTableCell4.Name = "xrTableCell4";
			this.xrTableCell4.StylePriority.UseFont = false;
			this.xrTableCell4.Text = "[JONumber]";
			this.xrTableCell4.Weight = 0.271769811934977;
			XRBindingCollection dataBindings5 = this.xrTableCell9.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.InvoiceSampleReceiveTestInvoice.ProvideDescription") };
			dataBindings5.AddRange(xRBinding);
			this.xrTableCell9.Dpi = 100f;
			this.xrTableCell9.Name = "xrTableCell9";
			this.xrTableCell9.Weight = 0.585982501021398;
			this.xrTableCell10.Dpi = 100f;
			this.xrTableCell10.Name = "xrTableCell10";
			this.xrTableCell10.Weight = 0.18558069704145;
			this.xrTableCell11.Dpi = 100f;
			this.xrTableCell11.Name = "xrTableCell11";
			this.xrTableCell11.Weight = 0.154973129199837;
			this.xrTableCell12.Dpi = 100f;
			this.xrTableCell12.Name = "xrTableCell12";
			this.xrTableCell12.Weight = 0.226870844603595;
			XRBindingCollection xRBindingCollections5 = this.xrTableCell13.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.InvoiceSampleReceiveTestInvoice.SRTTotal", "{0:n2}") };
			xRBindingCollections5.AddRange(xRBinding);
			this.xrTableCell13.Dpi = 100f;
			this.xrTableCell13.Name = "xrTableCell13";
			this.xrTableCell13.Padding = new PaddingInfo(5, 10, 0, 0, 100f);
			this.xrTableCell13.StylePriority.UsePadding = false;
			this.xrTableCell13.StylePriority.UseTextAlignment = false;
			this.xrTableCell13.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrTableCell13.Weight = 0.260706738827866;
			XRControlCollection controls2 = this.GroupHeader1.Controls;
			xRControlArrays = new XRControl[] { this.xrTable4 };
			controls2.AddRange(xRControlArrays);
			this.GroupHeader1.Dpi = 100f;
			this.GroupHeader1.HeightF = 35.00001f;
			this.GroupHeader1.Name = "GroupHeader1";
			this.GroupHeader1.RepeatEveryPage = true;
			this.xrTable4.BackColor = Color.Gainsboro;
			this.xrTable4.Borders = BorderSide.All;
			this.xrTable4.Dpi = 100f;
			this.xrTable4.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrTable4.LocationFloat = new PointFloat(29.37842f, 10.00001f);
			this.xrTable4.Name = "xrTable4";
			this.xrTable4.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection rows1 = this.xrTable4.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow6 };
			rows1.AddRange(xRTableRowArray);
			this.xrTable4.SizeF = new System.Drawing.SizeF(795.1752f, 25f);
			this.xrTable4.StylePriority.UseBackColor = false;
			this.xrTable4.StylePriority.UseBorders = false;
			this.xrTable4.StylePriority.UseFont = false;
			this.xrTable4.StylePriority.UsePadding = false;
			XRTableCellCollection xRTableCellCollections3 = this.xrTableRow6.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell3, this.xrTableCell14, this.xrTableCell15, this.xrTableCell16, this.xrTableCell17, this.xrTableCell18 };
			xRTableCellCollections3.AddRange(xRTableCellArray);
			this.xrTableRow6.Dpi = 100f;
			this.xrTableRow6.Name = "xrTableRow6";
			this.xrTableRow6.Weight = 11.5;
			this.xrTableCell3.Dpi = 100f;
			this.xrTableCell3.Name = "xrTableCell3";
			this.xrTableCell3.Text = "Items";
			this.xrTableCell3.Weight = 0.231693730918667;
			this.xrTableCell14.Dpi = 100f;
			this.xrTableCell14.Name = "xrTableCell14";
			this.xrTableCell14.Text = "Service Description";
			this.xrTableCell14.Weight = 0.499376347998816;
			this.xrTableCell15.Dpi = 100f;
			this.xrTableCell15.Name = "xrTableCell15";
			this.xrTableCell15.Text = "Qty";
			this.xrTableCell15.Weight = 0.158063741481593;
			this.xrTableCell16.Dpi = 100f;
			this.xrTableCell16.Name = "xrTableCell16";
			this.xrTableCell16.Text = "Unit";
			this.xrTableCell16.Weight = 0.132126704276021;
			this.xrTableCell17.Dpi = 100f;
			this.xrTableCell17.Name = "xrTableCell17";
			this.xrTableCell17.Text = "Unit Price";
			this.xrTableCell17.Weight = 0.193595770115411;
			this.xrTableCell18.Dpi = 100f;
			this.xrTableCell18.Name = "xrTableCell18";
			this.xrTableCell18.StylePriority.UseBackColor = false;
			this.xrTableCell18.Text = "Amount";
			this.xrTableCell18.Weight = 0.221767560358685;
			BandCollection bandCollections = this.DetailReport2.Bands;
			detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail3 };
			bandCollections.AddRange(detail1);
			this.DetailReport2.DataMember = "Invoice.InvoiceWorkOrderList";
			this.DetailReport2.DataSource = this.sqlDataSource1;
			this.DetailReport2.Dpi = 100f;
			this.DetailReport2.Level = 1;
			this.DetailReport2.Name = "DetailReport2";
			XRControlCollection xRControlCollection2 = this.Detail3.Controls;
			xRControlArrays = new XRControl[] { this.xrTable2 };
			xRControlCollection2.AddRange(xRControlArrays);
			this.Detail3.Dpi = 100f;
			this.Detail3.HeightF = 25f;
			this.Detail3.Name = "Detail3";
			this.xrTable2.Borders = BorderSide.Left | BorderSide.Right | BorderSide.Bottom;
			this.xrTable2.Dpi = 100f;
			this.xrTable2.LocationFloat = new PointFloat(29.38f, 0f);
			this.xrTable2.Name = "xrTable2";
			this.xrTable2.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection xRTableRowCollections1 = this.xrTable2.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow3 };
			xRTableRowCollections1.AddRange(xRTableRowArray);
			this.xrTable2.SizeF = new System.Drawing.SizeF(795.0118f, 25f);
			this.xrTable2.StylePriority.UseBorders = false;
			this.xrTable2.StylePriority.UsePadding = false;
			XRTableCellCollection cells4 = this.xrTableRow3.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell5, this.xrTableCell6, this.xrTableCell7, this.xrTableCell8, this.xrTableCell19, this.xrTableCell20 };
			cells4.AddRange(xRTableCellArray);
			this.xrTableRow3.Dpi = 100f;
			this.xrTableRow3.Name = "xrTableRow3";
			this.xrTableRow3.Weight = 11.5;
			XRBindingCollection dataBindings6 = this.xrTableCell5.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.InvoiceWorkOrderList.WONumber") };
			dataBindings6.AddRange(xRBinding);
			this.xrTableCell5.Dpi = 100f;
			this.xrTableCell5.Name = "xrTableCell5";
			this.xrTableCell5.Weight = 0.271765779240925;
			XRBindingCollection xRBindingCollections6 = this.xrTableCell6.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.InvoiceWorkOrderList.Description") };
			xRBindingCollections6.AddRange(xRBinding);
			this.xrTableCell6.Dpi = 100f;
			this.xrTableCell6.Name = "xrTableCell6";
			this.xrTableCell6.Weight = 0.585973521838421;
			this.xrTableCell7.Dpi = 100f;
			this.xrTableCell7.Name = "xrTableCell7";
			this.xrTableCell7.Weight = 0.185842982161816;
			this.xrTableCell8.Dpi = 100f;
			this.xrTableCell8.Name = "xrTableCell8";
			this.xrTableCell8.Weight = 0.154905236001927;
			this.xrTableCell19.Dpi = 100f;
			this.xrTableCell19.Name = "xrTableCell19";
			this.xrTableCell19.Weight = 0.226928790398174;
			XRBindingCollection dataBindings7 = this.xrTableCell20.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.InvoiceWorkOrderList.Amount", "{0:n2}") };
			dataBindings7.AddRange(xRBinding);
			this.xrTableCell20.Dpi = 100f;
			this.xrTableCell20.Name = "xrTableCell20";
			this.xrTableCell20.Padding = new PaddingInfo(5, 10, 0, 0, 100f);
			this.xrTableCell20.StylePriority.UsePadding = false;
			this.xrTableCell20.StylePriority.UseTextAlignment = false;
			this.xrTableCell20.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrTableCell20.Weight = 0.260706861901944;
			BandCollection bands1 = this.DetailReport1.Bands;
			detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail2 };
			bands1.AddRange(detail1);
			this.DetailReport1.Dpi = 100f;
			this.DetailReport1.Level = 2;
			this.DetailReport1.Name = "DetailReport1";
			XRControlCollection controls3 = this.Detail2.Controls;
			xRControlArrays = new XRControl[] { this.xrLabel21, this.xrLabel19 };
			controls3.AddRange(xRControlArrays);
			this.Detail2.Dpi = 100f;
			this.Detail2.HeightF = 20.83333f;
			this.Detail2.Name = "Detail2";
			this.xrLabel21.BackColor = Color.WhiteSmoke;
			this.xrLabel21.Borders = BorderSide.All;
			XRBindingCollection xRBindingCollections7 = this.xrLabel21.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "Invoice.NetAmount", "{0:n2}") };
			xRBindingCollections7.AddRange(xRBinding);
			this.xrLabel21.Dpi = 100f;
			this.xrLabel21.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrLabel21.LocationFloat = new PointFloat(701.8046f, 0.1874924f);
			this.xrLabel21.Name = "xrLabel21";
			this.xrLabel21.Padding = new PaddingInfo(2, 10, 0, 0, 100f);
			this.xrLabel21.SizeF = new System.Drawing.SizeF(123.0831f, 20.64583f);
			this.xrLabel21.StylePriority.UseBackColor = false;
			this.xrLabel21.StylePriority.UseBorders = false;
			this.xrLabel21.StylePriority.UseFont = false;
			this.xrLabel21.StylePriority.UsePadding = false;
			this.xrLabel21.StylePriority.UseTextAlignment = false;
			this.xrLabel21.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrLabel19.BackColor = Color.WhiteSmoke;
			this.xrLabel19.Borders = BorderSide.Left | BorderSide.Top | BorderSide.Bottom;
			this.xrLabel19.Dpi = 100f;
			this.xrLabel19.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrLabel19.LocationFloat = new PointFloat(433.8049f, 0.1874924f);
			this.xrLabel19.Name = "xrLabel19";
			this.xrLabel19.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel19.SizeF = new System.Drawing.SizeF(268.1248f, 20.64583f);
			this.xrLabel19.StylePriority.UseBackColor = false;
			this.xrLabel19.StylePriority.UseBorders = false;
			this.xrLabel19.StylePriority.UseFont = false;
			this.xrLabel19.StylePriority.UsePadding = false;
			this.xrLabel19.StylePriority.UseTextAlignment = false;
			this.xrLabel19.Text = "TOTAL INVOICE AMOUNT (QAR):";
			this.xrLabel19.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.InvoiceID.Description = "Parameter1";
			dynamicListLookUpSetting.DataAdapter = null;
			dynamicListLookUpSetting.DataMember = "Invoice";
			dynamicListLookUpSetting.DataSource = this.sqlDataSource1;
			dynamicListLookUpSetting.DisplayMember = "InvoiceNumber";
			dynamicListLookUpSetting.FilterString = null;
			dynamicListLookUpSetting.ValueMember = "InvoiceId";
			this.InvoiceID.LookUpSettings = dynamicListLookUpSetting;
			this.InvoiceID.Name = "InvoiceID";
			this.InvoiceID.Type = typeof(int);
			this.InvoiceID.ValueInfo = "0";
			this.JONumber.DataMember = "Invoice.InvoiceSampleReceiveTestInvoice";
			this.JONumber.Expression = " ('Job Order :') + [JobOrderNumber]";
			this.JONumber.Name = "JONumber";
			this.WONumber.DataMember = "Invoice.InvoiceWorkOrderList";
			this.WONumber.Expression = "('Work Order : ') + [WorkOrderNo]";
			this.WONumber.Name = "WONumber";
			this.xrLabel4.Dpi = 100f;
			this.xrLabel4.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel4.LocationFloat = new PointFloat(594.6489f, 20.83333f);
			this.xrLabel4.Name = "xrLabel4";
			this.xrLabel4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel4.SizeF = new System.Drawing.SizeF(116.8333f, 18f);
			this.xrLabel4.StyleName = "FieldCaption";
			this.xrLabel4.StylePriority.UseForeColor = false;
			this.xrLabel4.Text = "Checked by";
			this.xrLabel7.Dpi = 100f;
			this.xrLabel7.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel7.LocationFloat = new PointFloat(101.1667f, 20.83333f);
			this.xrLabel7.Name = "xrLabel7";
			this.xrLabel7.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel7.SizeF = new System.Drawing.SizeF(116.8333f, 18f);
			this.xrLabel7.StyleName = "FieldCaption";
			this.xrLabel7.StylePriority.UseForeColor = false;
			this.xrLabel7.Text = "Approved by";
			this.xrLabel10.BorderDashStyle = DevExpress.XtraPrinting.BorderDashStyle.Dot;
			this.xrLabel10.Borders = BorderSide.Top;
			this.xrLabel10.Dpi = 100f;
			this.xrLabel10.Font = new System.Drawing.Font("Arial", 5f, FontStyle.Bold);
			this.xrLabel10.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel10.LocationFloat = new PointFloat(81.5f, 54.91664f);
			this.xrLabel10.Name = "xrLabel10";
			this.xrLabel10.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel10.SizeF = new System.Drawing.SizeF(147.8333f, 18f);
			this.xrLabel10.StyleName = "FieldCaption";
			this.xrLabel10.StylePriority.UseBorderDashStyle = false;
			this.xrLabel10.StylePriority.UseBorders = false;
			this.xrLabel10.StylePriority.UseFont = false;
			this.xrLabel10.StylePriority.UseForeColor = false;
			this.xrLabel11.BorderDashStyle = DevExpress.XtraPrinting.BorderDashStyle.Dot;
			this.xrLabel11.Borders = BorderSide.Top;
			this.xrLabel11.Dpi = 100f;
			this.xrLabel11.Font = new System.Drawing.Font("Arial Narrow", 2.25f, FontStyle.Bold | FontStyle.Italic, GraphicsUnit.Point, 0);
			this.xrLabel11.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel11.LocationFloat = new PointFloat(578.9995f, 54.91664f);
			this.xrLabel11.Name = "xrLabel11";
			this.xrLabel11.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel11.SizeF = new System.Drawing.SizeF(143.6666f, 18f);
			this.xrLabel11.StyleName = "FieldCaption";
			this.xrLabel11.StylePriority.UseBorderDashStyle = false;
			this.xrLabel11.StylePriority.UseBorders = false;
			this.xrLabel11.StylePriority.UseFont = false;
			this.xrLabel11.StylePriority.UseForeColor = false;
			BandCollection bandCollections1 = base.Bands;
			detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail, this.TopMargin, this.BottomMargin, this.pageFooterBand1, this.reportHeaderBand1, this.DetailReport, this.DetailReport2, this.DetailReport1 };
			bandCollections1.AddRange(detail1);
			CalculatedFieldCollection calculatedFields = base.CalculatedFields;
			CalculatedField[] jONumber = new CalculatedField[] { this.JONumber, this.WONumber };
			calculatedFields.AddRange(jONumber);
			base.ComponentStorage.AddRange(new IComponent[] { this.sqlDataSource1 });
			base.DataMember = "Invoice";
			base.DataSource = this.sqlDataSource1;
			this.FilterString = "[InvoiceId] = ?InvoiceID";
			base.Margins = new System.Drawing.Printing.Margins(3, 1, 110, 73);
			base.Parameters.AddRange(new Parameter[] { this.InvoiceID });
			XRControlStyleSheet styleSheet = base.StyleSheet;
			XRControlStyle[] title = new XRControlStyle[] { this.Title, this.FieldCaption, this.PageInfo, this.DataField };
			styleSheet.AddRange(title);
			base.Version = "16.1";
			((ISupportInitialize)this.xrTable1).EndInit();
			((ISupportInitialize)this.xrTable3).EndInit();
			((ISupportInitialize)this.xrTable4).EndInit();
			((ISupportInitialize)this.xrTable2).EndInit();
			((ISupportInitialize)this).EndInit();
		}
	}
}