using DevExpress.DataAccess;
using DevExpress.DataAccess.Sql;
using DevExpress.Utils;
using DevExpress.XtraPrinting;
using DevExpress.XtraReports.Parameters;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Printing;
using System.Resources;

namespace PioneerLab.Reports
{
	public class Material_Information : XtraReport
	{
		private IContainer components;

		private DetailBand Detail;

		private TopMarginBand TopMargin;

		private BottomMarginBand BottomMargin;

		private XRLabel xrLabel1;

		private XRLabel xrLabel2;

		private XRLabel xrLabel3;

		private XRLabel xrLabel5;

		private XRLabel xrLabel6;

		private XRLabel xrLabel7;

		private XRLabel xrLabel8;

		private XRLabel xrLabel9;

		private XRCheckBox xrCheckBox1;

		private XRLabel xrLabel10;

		private XRLabel xrLabel12;

		private XRLabel xrLabel13;

		private XRLabel xrLabel14;

		private XRLabel xrLabel15;

		private SqlDataSource sqlDataSource1;

		private PageFooterBand pageFooterBand1;

		private XRPageInfo xrPageInfo1;

		private XRPageInfo xrPageInfo2;

		private ReportHeaderBand reportHeaderBand1;

		private XRControlStyle Title;

		private XRControlStyle FieldCaption;

		private XRControlStyle PageInfo;

		private XRControlStyle DataField;

		private DetailReportBand DetailReport;

		private DetailBand Detail1;

		private XRTable xrTable1;

		private XRTableRow xrTableRow1;

		private XRTableCell xrTableCell1;

		private XRTableCell xrTableCell2;

		private GroupHeaderBand GroupHeader1;

		private XRTable xrTable2;

		private XRTableRow xrTableRow2;

		private XRTableCell xrTableCell3;

		private XRTableCell xrTableCell4;

		private XRLabel xrLabel26;

		private PageHeaderBand PageHeader;

		private XRPictureBox xrPictureBox2;

		private Parameter Id;

		private XRLine xrLine2;

		private XRLabel xrLabel4;

		private XRLabel xrLabel11;

		private XRPictureBox xrPictureBox1;

		private XRLabel xrLabel16;

		private XRLabel xrLabel17;

		private XRLabel xrLabel18;

		private XRLine xrLine1;

		private XRLabel xrLabel19;

		public Material_Information()
		{
			this.InitializeComponent();
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			SelectQuery selectQuery = new SelectQuery();
			Column column = new Column();
			ColumnExpression columnExpression = new ColumnExpression();
			Table table = new Table();
			Column column1 = new Column();
			ColumnExpression columnExpression1 = new ColumnExpression();
			Column column2 = new Column();
			ColumnExpression columnExpression2 = new ColumnExpression();
			Column column3 = new Column();
			ColumnExpression columnExpression3 = new ColumnExpression();
			Column column4 = new Column();
			ColumnExpression columnExpression4 = new ColumnExpression();
			Column column5 = new Column();
			ColumnExpression columnExpression5 = new ColumnExpression();
			Column column6 = new Column();
			ColumnExpression columnExpression6 = new ColumnExpression();
			Column column7 = new Column();
			ColumnExpression columnExpression7 = new ColumnExpression();
			Column column8 = new Column();
			ColumnExpression columnExpression8 = new ColumnExpression();
			Table table1 = new Table();
			Column column9 = new Column();
			ColumnExpression columnExpression9 = new ColumnExpression();
			Column column10 = new Column();
			ColumnExpression columnExpression10 = new ColumnExpression();
			Column column11 = new Column();
			ColumnExpression columnExpression11 = new ColumnExpression();
			Join join = new Join();
			RelationColumnInfo relationColumnInfo = new RelationColumnInfo();
			SelectQuery selectQuery1 = new SelectQuery();
			Column column12 = new Column();
			ColumnExpression columnExpression12 = new ColumnExpression();
			Table table2 = new Table();
			Column column13 = new Column();
			ColumnExpression columnExpression13 = new ColumnExpression();
			Column column14 = new Column();
			ColumnExpression columnExpression14 = new ColumnExpression();
			Column column15 = new Column();
			ColumnExpression columnExpression15 = new ColumnExpression();
			Table table3 = new Table();
			Column column16 = new Column();
			ColumnExpression columnExpression16 = new ColumnExpression();
			Join join1 = new Join();
			RelationColumnInfo relationColumnInfo1 = new RelationColumnInfo();
			MasterDetailInfo masterDetailInfo = new MasterDetailInfo();
			RelationColumnInfo relationColumnInfo2 = new RelationColumnInfo();
			ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(Material_Information));
			DynamicListLookUpSettings dynamicListLookUpSetting = new DynamicListLookUpSettings();
			this.sqlDataSource1 = new SqlDataSource(this.components);
			this.Detail = new DetailBand();
			this.xrLabel1 = new XRLabel();
			this.xrLabel2 = new XRLabel();
			this.xrLabel3 = new XRLabel();
			this.xrLabel5 = new XRLabel();
			this.xrLabel6 = new XRLabel();
			this.xrLabel7 = new XRLabel();
			this.xrLabel8 = new XRLabel();
			this.xrLabel9 = new XRLabel();
			this.xrCheckBox1 = new XRCheckBox();
			this.xrLabel10 = new XRLabel();
			this.xrLabel12 = new XRLabel();
			this.xrLabel13 = new XRLabel();
			this.xrLabel14 = new XRLabel();
			this.xrLabel15 = new XRLabel();
			this.TopMargin = new TopMarginBand();
			this.xrLine2 = new XRLine();
			this.xrLabel4 = new XRLabel();
			this.xrLabel11 = new XRLabel();
			this.xrPictureBox1 = new XRPictureBox();
			this.xrLabel16 = new XRLabel();
			this.xrLabel17 = new XRLabel();
			this.xrLabel18 = new XRLabel();
			this.xrLine1 = new XRLine();
			this.xrLabel19 = new XRLabel();
			this.BottomMargin = new BottomMarginBand();
			this.xrPictureBox2 = new XRPictureBox();
			this.xrPageInfo2 = new XRPageInfo();
			this.xrPageInfo1 = new XRPageInfo();
			this.pageFooterBand1 = new PageFooterBand();
			this.reportHeaderBand1 = new ReportHeaderBand();
			this.Title = new XRControlStyle();
			this.FieldCaption = new XRControlStyle();
			this.PageInfo = new XRControlStyle();
			this.DataField = new XRControlStyle();
			this.DetailReport = new DetailReportBand();
			this.Detail1 = new DetailBand();
			this.xrTable1 = new XRTable();
			this.xrTableRow1 = new XRTableRow();
			this.xrTableCell1 = new XRTableCell();
			this.xrTableCell2 = new XRTableCell();
			this.GroupHeader1 = new GroupHeaderBand();
			this.xrTable2 = new XRTable();
			this.xrTableRow2 = new XRTableRow();
			this.xrTableCell3 = new XRTableCell();
			this.xrTableCell4 = new XRTableCell();
			this.xrLabel26 = new XRLabel();
			this.PageHeader = new PageHeaderBand();
			this.Id = new Parameter();
			((ISupportInitialize)this.xrTable1).BeginInit();
			((ISupportInitialize)this.xrTable2).BeginInit();
			((ISupportInitialize)this).BeginInit();
			this.sqlDataSource1.ConnectionName = "localhost_LabSys_Connection";
			this.sqlDataSource1.Name = "sqlDataSource1";
			columnExpression.ColumnName = "MaterialDetailsID";
			table.MetaSerializable = "30|30|125|200";
			table.Name = "MaterialsDetails";
			columnExpression.Table = table;
			column.Expression = columnExpression;
			columnExpression1.ColumnName = "FKMaterialTypeID";
			columnExpression1.Table = table;
			column1.Expression = columnExpression1;
			columnExpression2.ColumnName = "MaterialName";
			columnExpression2.Table = table;
			column2.Expression = columnExpression2;
			columnExpression3.ColumnName = "MaterialDescription";
			columnExpression3.Table = table;
			column3.Expression = columnExpression3;
			columnExpression4.ColumnName = "MaterialUse";
			columnExpression4.Table = table;
			column4.Expression = columnExpression4;
			columnExpression5.ColumnName = "StandardSpecs";
			columnExpression5.Table = table;
			column5.Expression = columnExpression5;
			columnExpression6.ColumnName = "StandardNumber";
			columnExpression6.Table = table;
			column6.Expression = columnExpression6;
			columnExpression7.ColumnName = "IsLocked";
			columnExpression7.Table = table;
			column7.Expression = columnExpression7;
			columnExpression8.ColumnName = "MaterialTypeID";
			table1.MetaSerializable = "185|30|125|120";
			table1.Name = "MaterialsTypes";
			columnExpression8.Table = table1;
			column8.Expression = columnExpression8;
			column9.Alias = "MaterialsTypes_MaterialName";
			columnExpression9.ColumnName = "MaterialName";
			columnExpression9.Table = table1;
			column9.Expression = columnExpression9;
			columnExpression10.ColumnName = "FKLabID";
			columnExpression10.Table = table1;
			column10.Expression = columnExpression10;
			column11.Alias = "MaterialsTypes_IsLocked";
			columnExpression11.ColumnName = "IsLocked";
			columnExpression11.Table = table1;
			column11.Expression = columnExpression11;
			selectQuery.Columns.Add(column);
			selectQuery.Columns.Add(column1);
			selectQuery.Columns.Add(column2);
			selectQuery.Columns.Add(column3);
			selectQuery.Columns.Add(column4);
			selectQuery.Columns.Add(column5);
			selectQuery.Columns.Add(column6);
			selectQuery.Columns.Add(column7);
			selectQuery.Columns.Add(column8);
			selectQuery.Columns.Add(column9);
			selectQuery.Columns.Add(column10);
			selectQuery.Columns.Add(column11);
			selectQuery.Name = "MaterialsDetails";
			relationColumnInfo.NestedKeyColumn = "MaterialTypeID";
			relationColumnInfo.ParentKeyColumn = "FKMaterialTypeID";
			join.KeyColumns.Add(relationColumnInfo);
			join.Nested = table1;
			join.Parent = table;
			selectQuery.Relations.Add(join);
			selectQuery.Tables.Add(table);
			selectQuery.Tables.Add(table1);
			columnExpression12.ColumnName = "MaterialTestID";
			table2.MetaSerializable = "30|30|125|100";
			table2.Name = "MaterialsDetailsTests";
			columnExpression12.Table = table2;
			column12.Expression = columnExpression12;
			columnExpression13.ColumnName = "FKMaterialDetailsID";
			columnExpression13.Table = table2;
			column13.Expression = columnExpression13;
			columnExpression14.ColumnName = "FKTestID";
			columnExpression14.Table = table2;
			column14.Expression = columnExpression14;
			columnExpression15.ColumnName = "StandardNumber";
			table3.MetaSerializable = "185|30|125|480";
			table3.Name = "TestsList";
			columnExpression15.Table = table3;
			column15.Expression = columnExpression15;
			columnExpression16.ColumnName = "TestName";
			columnExpression16.Table = table3;
			column16.Expression = columnExpression16;
			selectQuery1.Columns.Add(column12);
			selectQuery1.Columns.Add(column13);
			selectQuery1.Columns.Add(column14);
			selectQuery1.Columns.Add(column15);
			selectQuery1.Columns.Add(column16);
			selectQuery1.Name = "MaterialsDetailsTests";
			relationColumnInfo1.NestedKeyColumn = "TestID";
			relationColumnInfo1.ParentKeyColumn = "FKTestID";
			join1.KeyColumns.Add(relationColumnInfo1);
			join1.Nested = table3;
			join1.Parent = table2;
			selectQuery1.Relations.Add(join1);
			selectQuery1.Tables.Add(table2);
			selectQuery1.Tables.Add(table3);
			this.sqlDataSource1.Queries.AddRange(new SqlQuery[] { selectQuery, selectQuery1 });
			masterDetailInfo.DetailQueryName = "MaterialsDetailsTests";
			relationColumnInfo2.NestedKeyColumn = "FKMaterialDetailsID";
			relationColumnInfo2.ParentKeyColumn = "MaterialDetailsID";
			masterDetailInfo.KeyColumns.Add(relationColumnInfo2);
			masterDetailInfo.MasterQueryName = "MaterialsDetails";
			masterDetailInfo.Name = "FK_MaterialsDetailsTests_MaterialsDetails";
			this.sqlDataSource1.Relations.AddRange(new MasterDetailInfo[] { masterDetailInfo });
			this.sqlDataSource1.ResultSchemaSerializable = componentResourceManager.GetString("sqlDataSource1.ResultSchemaSerializable");
			XRControlCollection controls = this.Detail.Controls;
			XRControl[] xRControlArrays = new XRControl[] { this.xrLabel1, this.xrLabel2, this.xrLabel3, this.xrLabel5, this.xrLabel6, this.xrLabel7, this.xrLabel8, this.xrLabel9, this.xrCheckBox1, this.xrLabel10, this.xrLabel12, this.xrLabel13, this.xrLabel14, this.xrLabel15 };
			controls.AddRange(xRControlArrays);
			this.Detail.Dpi = 100f;
			this.Detail.HeightF = 149.7917f;
			this.Detail.KeepTogether = true;
			this.Detail.KeepTogetherWithDetailReports = true;
			this.Detail.Name = "Detail";
			this.Detail.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.Detail.PageBreak = DevExpress.XtraReports.UI.PageBreak.BeforeBand;
			this.Detail.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLabel1.Dpi = 100f;
			this.xrLabel1.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel1.LocationFloat = new PointFloat(394.75f, 48.54171f);
			this.xrLabel1.Name = "xrLabel1";
			this.xrLabel1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel1.SizeF = new System.Drawing.SizeF(162f, 18f);
			this.xrLabel1.StyleName = "FieldCaption";
			this.xrLabel1.StylePriority.UseForeColor = false;
			this.xrLabel1.Text = "Service Section:";
			this.xrLabel2.Dpi = 100f;
			this.xrLabel2.LocationFloat = new PointFloat(706.4167f, 0f);
			this.xrLabel2.Name = "xrLabel2";
			this.xrLabel2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel2.SizeF = new System.Drawing.SizeF(71.37503f, 23f);
			this.xrLabel2.StyleName = "FieldCaption";
			this.xrLabel2.Text = "Inactive";
			this.xrLabel3.Dpi = 100f;
			this.xrLabel3.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel3.LocationFloat = new PointFloat(394.7501f, 77.45835f);
			this.xrLabel3.Name = "xrLabel3";
			this.xrLabel3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel3.SizeF = new System.Drawing.SizeF(162f, 18f);
			this.xrLabel3.StyleName = "FieldCaption";
			this.xrLabel3.StylePriority.UseForeColor = false;
			this.xrLabel3.Text = "Material Description:";
			this.xrLabel5.Dpi = 100f;
			this.xrLabel5.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel5.LocationFloat = new PointFloat(9.999998f, 48.54171f);
			this.xrLabel5.Name = "xrLabel5";
			this.xrLabel5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel5.SizeF = new System.Drawing.SizeF(137f, 18f);
			this.xrLabel5.StyleName = "FieldCaption";
			this.xrLabel5.StylePriority.UseForeColor = false;
			this.xrLabel5.Text = "Material Name:";
			this.xrLabel6.Dpi = 100f;
			this.xrLabel6.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel6.LocationFloat = new PointFloat(10.00001f, 77.45835f);
			this.xrLabel6.Name = "xrLabel6";
			this.xrLabel6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel6.SizeF = new System.Drawing.SizeF(137f, 18f);
			this.xrLabel6.StyleName = "FieldCaption";
			this.xrLabel6.StylePriority.UseForeColor = false;
			this.xrLabel6.Text = "Material Use:";
			this.xrLabel7.Dpi = 100f;
			this.xrLabel7.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel7.LocationFloat = new PointFloat(394.7501f, 108.08f);
			this.xrLabel7.Name = "xrLabel7";
			this.xrLabel7.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel7.SizeF = new System.Drawing.SizeF(162f, 18f);
			this.xrLabel7.StyleName = "FieldCaption";
			this.xrLabel7.StylePriority.UseForeColor = false;
			this.xrLabel7.Text = "Standard Number:";
			this.xrLabel8.Dpi = 100f;
			this.xrLabel8.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel8.LocationFloat = new PointFloat(10.00001f, 108.08f);
			this.xrLabel8.Name = "xrLabel8";
			this.xrLabel8.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel8.SizeF = new System.Drawing.SizeF(137f, 18f);
			this.xrLabel8.StyleName = "FieldCaption";
			this.xrLabel8.StylePriority.UseForeColor = false;
			this.xrLabel8.Text = "Specification value:";
			this.xrLabel9.Borders = BorderSide.All;
			XRBindingCollection dataBindings = this.xrLabel9.DataBindings;
			XRBinding[] xRBinding = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.MaterialsTypes_MaterialName") };
			dataBindings.AddRange(xRBinding);
			this.xrLabel9.Dpi = 100f;
			this.xrLabel9.LocationFloat = new PointFloat(556.7501f, 48.54172f);
			this.xrLabel9.Name = "xrLabel9";
			this.xrLabel9.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel9.SizeF = new System.Drawing.SizeF(221.0417f, 17.99999f);
			this.xrLabel9.StyleName = "DataField";
			this.xrLabel9.StylePriority.UseBorders = false;
			XRBindingCollection xRBindingCollections = this.xrCheckBox1.DataBindings;
			XRBinding[] xRBindingArray = new XRBinding[] { new XRBinding("CheckState", null, "MaterialsDetails.IsLocked") };
			xRBindingCollections.AddRange(xRBindingArray);
			this.xrCheckBox1.Dpi = 100f;
			this.xrCheckBox1.LocationFloat = new PointFloat(679.1251f, 0f);
			this.xrCheckBox1.Name = "xrCheckBox1";
			this.xrCheckBox1.SizeF = new System.Drawing.SizeF(27.29166f, 23f);
			this.xrCheckBox1.StyleName = "DataField";
			this.xrLabel10.Borders = BorderSide.All;
			XRBindingCollection dataBindings1 = this.xrLabel10.DataBindings;
			XRBinding[] xRBinding1 = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.MaterialDescription") };
			dataBindings1.AddRange(xRBinding1);
			this.xrLabel10.Dpi = 100f;
			this.xrLabel10.LocationFloat = new PointFloat(556.7501f, 77.45835f);
			this.xrLabel10.Name = "xrLabel10";
			this.xrLabel10.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel10.SizeF = new System.Drawing.SizeF(221.0417f, 18f);
			this.xrLabel10.StyleName = "DataField";
			this.xrLabel10.StylePriority.UseBorders = false;
			this.xrLabel10.Text = "xrLabel10";
			this.xrLabel12.Borders = BorderSide.All;
			XRBindingCollection xRBindingCollections1 = this.xrLabel12.DataBindings;
			XRBinding[] xRBindingArray1 = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.MaterialName") };
			xRBindingCollections1.AddRange(xRBindingArray1);
			this.xrLabel12.Dpi = 100f;
			this.xrLabel12.LocationFloat = new PointFloat(147f, 48.54171f);
			this.xrLabel12.Name = "xrLabel12";
			this.xrLabel12.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel12.SizeF = new System.Drawing.SizeF(217.6251f, 18f);
			this.xrLabel12.StyleName = "DataField";
			this.xrLabel12.StylePriority.UseBorders = false;
			this.xrLabel12.Text = "xrLabel12";
			this.xrLabel13.Borders = BorderSide.All;
			XRBindingCollection dataBindings2 = this.xrLabel13.DataBindings;
			XRBinding[] xRBinding2 = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.MaterialUse") };
			dataBindings2.AddRange(xRBinding2);
			this.xrLabel13.Dpi = 100f;
			this.xrLabel13.LocationFloat = new PointFloat(147f, 77.45835f);
			this.xrLabel13.Name = "xrLabel13";
			this.xrLabel13.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel13.SizeF = new System.Drawing.SizeF(217.6251f, 18f);
			this.xrLabel13.StyleName = "DataField";
			this.xrLabel13.StylePriority.UseBorders = false;
			this.xrLabel13.Text = "xrLabel13";
			this.xrLabel14.Borders = BorderSide.All;
			XRBindingCollection xRBindingCollections2 = this.xrLabel14.DataBindings;
			XRBinding[] xRBindingArray2 = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.StandardNumber") };
			xRBindingCollections2.AddRange(xRBindingArray2);
			this.xrLabel14.Dpi = 100f;
			this.xrLabel14.LocationFloat = new PointFloat(556.7501f, 108.08f);
			this.xrLabel14.Name = "xrLabel14";
			this.xrLabel14.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel14.SizeF = new System.Drawing.SizeF(221.0417f, 18f);
			this.xrLabel14.StyleName = "DataField";
			this.xrLabel14.StylePriority.UseBorders = false;
			this.xrLabel14.Text = "xrLabel14";
			this.xrLabel15.Borders = BorderSide.All;
			XRBindingCollection dataBindings3 = this.xrLabel15.DataBindings;
			XRBinding[] xRBinding3 = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.StandardSpecs") };
			dataBindings3.AddRange(xRBinding3);
			this.xrLabel15.Dpi = 100f;
			this.xrLabel15.LocationFloat = new PointFloat(147f, 108.08f);
			this.xrLabel15.Name = "xrLabel15";
			this.xrLabel15.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel15.SizeF = new System.Drawing.SizeF(217.6251f, 18f);
			this.xrLabel15.StyleName = "DataField";
			this.xrLabel15.StylePriority.UseBorders = false;
			this.xrLabel15.Text = "xrLabel15";
			XRControlCollection xRControlCollection = this.TopMargin.Controls;
			XRControl[] xRControlArrays1 = new XRControl[] { this.xrLine2, this.xrLabel4, this.xrLabel11, this.xrPictureBox1, this.xrLabel16, this.xrLabel17, this.xrLabel18, this.xrLine1, this.xrLabel19 };
			xRControlCollection.AddRange(xRControlArrays1);
			this.TopMargin.Dpi = 100f;
			this.TopMargin.HeightF = 130f;
			this.TopMargin.Name = "TopMargin";
			this.TopMargin.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.TopMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLine2.Dpi = 100f;
			this.xrLine2.ForeColor = Color.FromArgb(32, 150, 159);
			this.xrLine2.LocationFloat = new PointFloat(540.1331f, 99.47916f);
			this.xrLine2.Name = "xrLine2";
			this.xrLine2.SizeF = new System.Drawing.SizeF(300.4026f, 13f);
			this.xrLine2.StylePriority.UseForeColor = false;
			this.xrLabel4.BackColor = Color.White;
			this.xrLabel4.Dpi = 100f;
			this.xrLabel4.Font = new System.Drawing.Font("Times New Roman", 11f, FontStyle.Bold);
			this.xrLabel4.ForeColor = Color.FromArgb(45, 84, 108);
			this.xrLabel4.LocationFloat = new PointFloat(565.4379f, 71.52086f);
			this.xrLabel4.Name = "xrLabel4";
			this.xrLabel4.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel4.SizeF = new System.Drawing.SizeF(249.9936f, 22.99997f);
			this.xrLabel4.StylePriority.UseBackColor = false;
			this.xrLabel4.StylePriority.UseFont = false;
			this.xrLabel4.StylePriority.UseForeColor = false;
			this.xrLabel4.StylePriority.UsePadding = false;
			this.xrLabel4.StylePriority.UseTextAlignment = false;
			this.xrLabel4.Text = "اختبارات مواقع - تصميم خلطات - دراسات تربة";
			this.xrLabel4.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrLabel11.BackColor = Color.White;
			this.xrLabel11.Dpi = 100f;
			this.xrLabel11.Font = new System.Drawing.Font("Times New Roman", 11f, FontStyle.Bold);
			this.xrLabel11.ForeColor = Color.FromArgb(45, 84, 108);
			this.xrLabel11.LocationFloat = new PointFloat(565.4379f, 17.52084f);
			this.xrLabel11.Name = "xrLabel11";
			this.xrLabel11.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel11.SizeF = new System.Drawing.SizeF(249.9937f, 24f);
			this.xrLabel11.StylePriority.UseBackColor = false;
			this.xrLabel11.StylePriority.UseFont = false;
			this.xrLabel11.StylePriority.UseForeColor = false;
			this.xrLabel11.StylePriority.UsePadding = false;
			this.xrLabel11.StylePriority.UseTextAlignment = false;
			this.xrLabel11.Text = "إختبارات ميكانيكية وفزيائية  وكميائية لمواد البناء";
			this.xrLabel11.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrPictureBox1.Dpi = 100f;
			this.xrPictureBox1.Image = (Image)componentResourceManager.GetObject("xrPictureBox1.Image");
			this.xrPictureBox1.LocationFloat = new PointFloat(340.5699f, 17.52084f);
			this.xrPictureBox1.Name = "xrPictureBox1";
			this.xrPictureBox1.SizeF = new System.Drawing.SizeF(189.2164f, 94.95832f);
			this.xrLabel16.BackColor = Color.White;
			this.xrLabel16.Dpi = 100f;
			this.xrLabel16.Font = new System.Drawing.Font("Times New Roman", 11f, FontStyle.Bold);
			this.xrLabel16.ForeColor = Color.FromArgb(45, 84, 108);
			this.xrLabel16.LocationFloat = new PointFloat(565.4379f, 43.47918f);
			this.xrLabel16.Name = "xrLabel16";
			this.xrLabel16.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel16.SizeF = new System.Drawing.SizeF(249.9937f, 22.99997f);
			this.xrLabel16.StylePriority.UseBackColor = false;
			this.xrLabel16.StylePriority.UseFont = false;
			this.xrLabel16.StylePriority.UseForeColor = false;
			this.xrLabel16.StylePriority.UsePadding = false;
			this.xrLabel16.StylePriority.UseTextAlignment = false;
			this.xrLabel16.Text = "تربة - اسفلت - حصي - كونكريت - اسمنت - ماء";
			this.xrLabel16.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrLabel17.BackColor = Color.White;
			this.xrLabel17.Dpi = 100f;
			this.xrLabel17.Font = new System.Drawing.Font("Times New Roman", 9f, FontStyle.Bold);
			this.xrLabel17.ForeColor = Color.FromArgb(45, 84, 103);
			this.xrLabel17.LocationFloat = new PointFloat(3.464294f, 41.52085f);
			this.xrLabel17.Name = "xrLabel17";
			this.xrLabel17.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel17.SizeF = new System.Drawing.SizeF(310.5137f, 25f);
			this.xrLabel17.StylePriority.UseBackColor = false;
			this.xrLabel17.StylePriority.UseFont = false;
			this.xrLabel17.StylePriority.UseForeColor = false;
			this.xrLabel17.StylePriority.UsePadding = false;
			this.xrLabel17.StylePriority.UseTextAlignment = false;
			this.xrLabel17.Text = "Soil - Asphalt - Aggregate - Concrete - Cement - Water";
			this.xrLabel17.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLabel18.BackColor = Color.White;
			this.xrLabel18.Dpi = 100f;
			this.xrLabel18.Font = new System.Drawing.Font("Times New Roman", 9f, FontStyle.Bold);
			this.xrLabel18.ForeColor = Color.FromArgb(45, 84, 103);
			this.xrLabel18.LocationFloat = new PointFloat(3.464294f, 66.52084f);
			this.xrLabel18.Name = "xrLabel18";
			this.xrLabel18.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel18.SizeF = new System.Drawing.SizeF(288.8611f, 24f);
			this.xrLabel18.StylePriority.UseBackColor = false;
			this.xrLabel18.StylePriority.UseFont = false;
			this.xrLabel18.StylePriority.UseForeColor = false;
			this.xrLabel18.StylePriority.UsePadding = false;
			this.xrLabel18.StylePriority.UseTextAlignment = false;
			this.xrLabel18.Text = "Site testing - Material design mixes - Soil study";
			this.xrLabel18.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLine1.Dpi = 100f;
			this.xrLine1.ForeColor = Color.FromArgb(32, 150, 159);
			this.xrLine1.LocationFloat = new PointFloat(4.326614f, 99.47916f);
			this.xrLine1.Name = "xrLine1";
			this.xrLine1.SizeF = new System.Drawing.SizeF(300.4026f, 13f);
			this.xrLine1.StylePriority.UseForeColor = false;
			this.xrLabel19.BackColor = Color.White;
			this.xrLabel19.Dpi = 100f;
			this.xrLabel19.Font = new System.Drawing.Font("Times New Roman", 9f, FontStyle.Bold);
			this.xrLabel19.ForeColor = Color.FromArgb(45, 84, 103);
			this.xrLabel19.LocationFloat = new PointFloat(3.464294f, 17.52084f);
			this.xrLabel19.Name = "xrLabel19";
			this.xrLabel19.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel19.SizeF = new System.Drawing.SizeF(285.9722f, 24f);
			this.xrLabel19.StylePriority.UseBackColor = false;
			this.xrLabel19.StylePriority.UseFont = false;
			this.xrLabel19.StylePriority.UseForeColor = false;
			this.xrLabel19.StylePriority.UsePadding = false;
			this.xrLabel19.StylePriority.UseTextAlignment = false;
			this.xrLabel19.Text = "Mechanical , physical and chimical material testing";
			this.xrLabel19.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRControlCollection controls1 = this.BottomMargin.Controls;
			XRControl[] xRControlArrays2 = new XRControl[] { this.xrPictureBox2, this.xrPageInfo2, this.xrPageInfo1 };
			controls1.AddRange(xRControlArrays2);
			this.BottomMargin.Dpi = 100f;
			this.BottomMargin.HeightF = 114.0417f;
			this.BottomMargin.Name = "BottomMargin";
			this.BottomMargin.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.BottomMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrPictureBox2.Dpi = 100f;
			this.xrPictureBox2.Image = (Image)componentResourceManager.GetObject("xrPictureBox2.Image");
			this.xrPictureBox2.LocationFloat = new PointFloat(135.5f, 0f);
			this.xrPictureBox2.Name = "xrPictureBox2";
			this.xrPictureBox2.SizeF = new System.Drawing.SizeF(581.3381f, 74.20829f);
			this.xrPageInfo2.Dpi = 100f;
			this.xrPageInfo2.Format = "Page {0} of {1}";
			this.xrPageInfo2.LocationFloat = new PointFloat(521.0001f, 91.04169f);
			this.xrPageInfo2.Name = "xrPageInfo2";
			this.xrPageInfo2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrPageInfo2.SizeF = new System.Drawing.SizeF(313f, 23f);
			this.xrPageInfo2.StyleName = "PageInfo";
			this.xrPageInfo2.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrPageInfo1.Dpi = 100f;
			this.xrPageInfo1.LocationFloat = new PointFloat(1.478004f, 91.04169f);
			this.xrPageInfo1.Name = "xrPageInfo1";
			this.xrPageInfo1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrPageInfo1.PageInfo = DevExpress.XtraPrinting.PageInfo.DateTime;
			this.xrPageInfo1.SizeF = new System.Drawing.SizeF(313f, 23f);
			this.xrPageInfo1.StyleName = "PageInfo";
			this.pageFooterBand1.Dpi = 100f;
			this.pageFooterBand1.HeightF = 9.208298f;
			this.pageFooterBand1.Name = "pageFooterBand1";
			this.reportHeaderBand1.Dpi = 100f;
			this.reportHeaderBand1.HeightF = 0f;
			this.reportHeaderBand1.Name = "reportHeaderBand1";
			this.Title.BackColor = Color.Transparent;
			this.Title.BorderColor = Color.Black;
			this.Title.Borders = BorderSide.None;
			this.Title.BorderWidth = 1f;
			this.Title.Font = new System.Drawing.Font("Times New Roman", 20f, FontStyle.Bold);
			this.Title.ForeColor = Color.Maroon;
			this.Title.Name = "Title";
			this.FieldCaption.BackColor = Color.Transparent;
			this.FieldCaption.BorderColor = Color.Black;
			this.FieldCaption.Borders = BorderSide.None;
			this.FieldCaption.BorderWidth = 1f;
			this.FieldCaption.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Bold);
			this.FieldCaption.ForeColor = Color.Maroon;
			this.FieldCaption.Name = "FieldCaption";
			this.PageInfo.BackColor = Color.Transparent;
			this.PageInfo.BorderColor = Color.Black;
			this.PageInfo.Borders = BorderSide.None;
			this.PageInfo.BorderWidth = 1f;
			this.PageInfo.Font = new System.Drawing.Font("Times New Roman", 10f, FontStyle.Bold);
			this.PageInfo.ForeColor = Color.Black;
			this.PageInfo.Name = "PageInfo";
			this.DataField.BackColor = Color.Transparent;
			this.DataField.BorderColor = Color.Black;
			this.DataField.Borders = BorderSide.None;
			this.DataField.BorderWidth = 1f;
			this.DataField.Font = new System.Drawing.Font("Times New Roman", 10f);
			this.DataField.ForeColor = Color.Black;
			this.DataField.Name = "DataField";
			this.DataField.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			BandCollection bands = this.DetailReport.Bands;
			DevExpress.XtraReports.UI.Band[] detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail1, this.GroupHeader1 };
			bands.AddRange(detail1);
			this.DetailReport.DataMember = "MaterialsDetails.FK_MaterialsDetailsTests_MaterialsDetails";
			this.DetailReport.DataSource = this.sqlDataSource1;
			this.DetailReport.Dpi = 100f;
			this.DetailReport.Level = 0;
			this.DetailReport.Name = "DetailReport";
			XRControlCollection xRControlCollection1 = this.Detail1.Controls;
			xRControlArrays = new XRControl[] { this.xrTable1 };
			xRControlCollection1.AddRange(xRControlArrays);
			this.Detail1.Dpi = 100f;
			this.Detail1.HeightF = 25f;
			this.Detail1.Name = "Detail1";
			this.xrTable1.Borders = BorderSide.Left | BorderSide.Right | BorderSide.Bottom;
			this.xrTable1.Dpi = 100f;
			this.xrTable1.LocationFloat = new PointFloat(121.875f, 0f);
			this.xrTable1.Name = "xrTable1";
			XRTableRowCollection rows = this.xrTable1.Rows;
			XRTableRow[] xRTableRowArray = new XRTableRow[] { this.xrTableRow1 };
			rows.AddRange(xRTableRowArray);
			this.xrTable1.SizeF = new System.Drawing.SizeF(484.5834f, 25f);
			this.xrTable1.StylePriority.UseBorders = false;
			this.xrTable1.StylePriority.UseTextAlignment = false;
			this.xrTable1.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			XRTableCellCollection cells = this.xrTableRow1.Cells;
			XRTableCell[] xRTableCellArray = new XRTableCell[] { this.xrTableCell1, this.xrTableCell2 };
			cells.AddRange(xRTableCellArray);
			this.xrTableRow1.Dpi = 100f;
			this.xrTableRow1.Name = "xrTableRow1";
			this.xrTableRow1.Weight = 11.5;
			XRBindingCollection xRBindingCollections3 = this.xrTableCell1.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.FK_MaterialsDetailsTests_MaterialsDetails.TestName") };
			xRBindingCollections3.AddRange(xRBinding);
			this.xrTableCell1.Dpi = 100f;
			this.xrTableCell1.Name = "xrTableCell1";
			this.xrTableCell1.Text = "xrTableCell1";
			this.xrTableCell1.Weight = 0.155038759689922;
			XRBindingCollection dataBindings4 = this.xrTableCell2.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "MaterialsDetails.FK_MaterialsDetailsTests_MaterialsDetails.StandardNumber") };
			dataBindings4.AddRange(xRBinding);
			this.xrTableCell2.Dpi = 100f;
			this.xrTableCell2.Name = "xrTableCell2";
			this.xrTableCell2.Text = "xrTableCell2";
			this.xrTableCell2.Weight = 0.155038759689922;
			XRControlCollection controls2 = this.GroupHeader1.Controls;
			xRControlArrays = new XRControl[] { this.xrTable2 };
			controls2.AddRange(xRControlArrays);
			this.GroupHeader1.Dpi = 100f;
			this.GroupHeader1.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.GroupHeader1.HeightF = 35.00001f;
			this.GroupHeader1.Name = "GroupHeader1";
			this.GroupHeader1.RepeatEveryPage = true;
			this.GroupHeader1.StylePriority.UseFont = false;
			this.GroupHeader1.StylePriority.UseTextAlignment = false;
			this.GroupHeader1.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrTable2.BackColor = SystemColors.ScrollBar;
			this.xrTable2.Borders = BorderSide.All;
			this.xrTable2.Dpi = 100f;
			this.xrTable2.LocationFloat = new PointFloat(121.875f, 10.00001f);
			this.xrTable2.Name = "xrTable2";
			XRTableRowCollection xRTableRowCollections = this.xrTable2.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow2 };
			xRTableRowCollections.AddRange(xRTableRowArray);
			this.xrTable2.SizeF = new System.Drawing.SizeF(484.5833f, 25f);
			this.xrTable2.StylePriority.UseBackColor = false;
			this.xrTable2.StylePriority.UseBorders = false;
			XRTableCellCollection xRTableCellCollections = this.xrTableRow2.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell3, this.xrTableCell4 };
			xRTableCellCollections.AddRange(xRTableCellArray);
			this.xrTableRow2.Dpi = 100f;
			this.xrTableRow2.Name = "xrTableRow2";
			this.xrTableRow2.Weight = 11.5;
			this.xrTableCell3.Dpi = 100f;
			this.xrTableCell3.Name = "xrTableCell3";
			this.xrTableCell3.Text = "Service Name";
			this.xrTableCell3.Weight = 0.155038759689922;
			this.xrTableCell4.Dpi = 100f;
			this.xrTableCell4.Name = "xrTableCell4";
			this.xrTableCell4.Text = "Standard Number";
			this.xrTableCell4.Weight = 0.155038759689922;
			this.xrLabel26.Dpi = 100f;
			this.xrLabel26.LocationFloat = new PointFloat(101.125f, 10.00001f);
			this.xrLabel26.Name = "xrLabel26";
			this.xrLabel26.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel26.SizeF = new System.Drawing.SizeF(638f, 33f);
			this.xrLabel26.StyleName = "Title";
			this.xrLabel26.StylePriority.UseTextAlignment = false;
			this.xrLabel26.Text = "Material Information";
			this.xrLabel26.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			XRControlCollection xRControlCollection2 = this.PageHeader.Controls;
			xRControlArrays = new XRControl[] { this.xrLabel26 };
			xRControlCollection2.AddRange(xRControlArrays);
			this.PageHeader.Dpi = 100f;
			this.PageHeader.HeightF = 65.625f;
			this.PageHeader.Name = "PageHeader";
			this.Id.Description = "Id";
			dynamicListLookUpSetting.DataAdapter = null;
			dynamicListLookUpSetting.DataMember = "MaterialsDetails";
			dynamicListLookUpSetting.DataSource = this.sqlDataSource1;
			dynamicListLookUpSetting.DisplayMember = "MaterialName";
			dynamicListLookUpSetting.FilterString = null;
			dynamicListLookUpSetting.ValueMember = "MaterialDetailsID";
			this.Id.LookUpSettings = dynamicListLookUpSetting;
			this.Id.Name = "Id";
			this.Id.Type = typeof(int);
			this.Id.ValueInfo = "0";
			BandCollection bandCollections = base.Bands;
			detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail, this.TopMargin, this.BottomMargin, this.pageFooterBand1, this.reportHeaderBand1, this.DetailReport, this.PageHeader };
			bandCollections.AddRange(detail1);
			base.ComponentStorage.AddRange(new IComponent[] { this.sqlDataSource1 });
			base.DataMember = "MaterialsDetails";
			base.DataSource = this.sqlDataSource1;
			this.FilterString = "[MaterialDetailsID] = ?Id";
			base.Margins = new System.Drawing.Printing.Margins(1, 5, 130, 114);
			base.Parameters.AddRange(new Parameter[] { this.Id });
			XRControlStyleSheet styleSheet = base.StyleSheet;
			XRControlStyle[] title = new XRControlStyle[] { this.Title, this.FieldCaption, this.PageInfo, this.DataField };
			styleSheet.AddRange(title);
			base.Version = "16.1";
			((ISupportInitialize)this.xrTable1).EndInit();
			((ISupportInitialize)this.xrTable2).EndInit();
			((ISupportInitialize)this).EndInit();
		}
	}
}