using DevExpress.DataAccess;
using DevExpress.DataAccess.Sql;
using DevExpress.Utils;
using DevExpress.XtraPrinting;
using DevExpress.XtraReports.Parameters;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Printing;
using System.Resources;

namespace PioneerLab.Reports
{
	public class RSSReport : XtraReport
	{
		private IContainer components;

		private DetailBand Detail;

		private TopMarginBand TopMargin;

		private BottomMarginBand BottomMargin;

		private XRLabel xrLabel1;

		private XRLabel xrLabel2;

		private XRLabel xrLabel3;

		private XRLabel xrLabel9;

		private XRLabel xrLabel11;

		private XRLabel xrLabel12;

		private XRLabel xrLabel19;

		private XRLabel xrLabel20;

		private XRLabel xrLabel21;

		private XRLabel xrLabel27;

		private XRLabel xrLabel29;

		private XRLabel xrLabel30;

		private SqlDataSource sqlDataSource1;

		private PageFooterBand pageFooterBand1;

		private ReportHeaderBand reportHeaderBand1;

		private XRLabel xrLabel37;

		private XRControlStyle Title;

		private XRControlStyle FieldCaption;

		private XRControlStyle PageInfo;

		private XRControlStyle DataField;

		private XRLabel xrLabel5;

		private XRLabel xrLabel4;

		private XRTable xrTable2;

		private XRTableRow xrTableRow3;

		private XRTableCell xrTableCell5;

		private XRTableCell xrTableCell6;

		private XRTableCell xrTableCell7;

		private XRTableCell xrTableCell14;

		private XRTableRow xrTableRow4;

		private XRTableCell xrTableCell8;

		private XRTableCell xrTableCell9;

		private XRTableCell xrTableCell10;

		private XRTableCell xrTableCell15;

		private XRTableRow xrTableRow5;

		private XRTableCell xrTableCell11;

		private XRTableCell xrTableCell12;

		private XRLabel xrLabel44;

		private XRLabel xrLabel45;

		private XRTable xrTable1;

		private XRTableRow xrTableRow1;

		private XRTableCell xrTableCell1;

		private XRTableCell xrTableCell2;

		private XRTableRow xrTableRow2;

		private XRTableCell xrTableCell3;

		private XRTableCell xrTableCell4;

		private DetailReportBand DetailReport;

		private DetailBand Detail1;

		private XRTable xrTable4;

		private XRTableRow xrTableRow7;

		private XRTableCell xrTableCell17;

		private XRTableCell xrTableCell18;

		private GroupHeaderBand GroupHeader1;

		private XRTable xrTable3;

		private XRTableRow xrTableRow6;

		private XRTableCell xrTableCell13;

		private XRTableCell xrTableCell16;

		private DetailReportBand DetailReport1;

		private DetailBand Detail2;

		private XRLine xrLine4;

		private XRLine xrLine1;

		private XRLabel xrLabel14;

		private XRLabel xrLabel8;

		private XRLabel xrLabel7;

		private XRLabel xrLabel6;

		private XRPageInfo xrPageInfo3;

		private XRPageInfo xrPageInfo4;

		private XRPictureBox xrPictureBox2;

		private XRTable xrTable5;

		private XRTableRow xrTableRow8;

		private XRTableCell xrTableCell19;

		private XRTableCell xrTableCell20;

		private XRTableCell xrTableCell21;

		private XRTableCell xrTableCell22;

		private XRTableRow xrTableRow9;

		private XRTableCell xrTableCell23;

		private XRTableCell xrTableCell24;

		private XRTableCell xrTableCell25;

		private XRTableCell xrTableCell26;

		private XRTableRow xrTableRow10;

		private XRTableCell xrTableCell27;

		private XRTableCell xrTableCell29;

		private XRTableCell xrTableCell30;

		private XRTableCell xrTableCell28;

		private XRLabel xrLabel10;

		private XRLine xrLine7;

		private XRLabel xrLabel16;

		private XRLabel xrLabel13;

		private XRLabel xrLabel15;

		private XRLine xrLine5;

		private XRLine xrLine6;

		private PageHeaderBand PageHeader;

		private Parameter RSSID;

		private XRLine xrLine8;

		private XRLine xrLine2;

		private XRLabel xrLabel17;

		private XRLabel xrLabel18;

		private XRPictureBox xrPictureBox1;

		private XRLabel xrLabel22;

		private XRLabel xrLabel23;

		private XRLabel xrLabel24;

		private XRLine xrLine3;

		private XRLabel xrLabel25;

		public RSSReport()
		{
			this.InitializeComponent();
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			SelectQuery selectQuery = new SelectQuery();
			Column column = new Column();
			ColumnExpression columnExpression = new ColumnExpression();
			Table table = new Table();
			Column column1 = new Column();
			ColumnExpression columnExpression1 = new ColumnExpression();
			Column column2 = new Column();
			ColumnExpression columnExpression2 = new ColumnExpression();
			Column column3 = new Column();
			ColumnExpression columnExpression3 = new ColumnExpression();
			Column column4 = new Column();
			ColumnExpression columnExpression4 = new ColumnExpression();
			Column column5 = new Column();
			ColumnExpression columnExpression5 = new ColumnExpression();
			Column column6 = new Column();
			ColumnExpression columnExpression6 = new ColumnExpression();
			Column column7 = new Column();
			ColumnExpression columnExpression7 = new ColumnExpression();
			Column column8 = new Column();
			ColumnExpression columnExpression8 = new ColumnExpression();
			Column column9 = new Column();
			ColumnExpression columnExpression9 = new ColumnExpression();
			Column column10 = new Column();
			ColumnExpression columnExpression10 = new ColumnExpression();
			Column column11 = new Column();
			ColumnExpression columnExpression11 = new ColumnExpression();
			Column column12 = new Column();
			ColumnExpression columnExpression12 = new ColumnExpression();
			Column column13 = new Column();
			ColumnExpression columnExpression13 = new ColumnExpression();
			Column column14 = new Column();
			ColumnExpression columnExpression14 = new ColumnExpression();
			Table table1 = new Table();
			Column column15 = new Column();
			ColumnExpression columnExpression15 = new ColumnExpression();
			Table table2 = new Table();
			Column column16 = new Column();
			ColumnExpression columnExpression16 = new ColumnExpression();
			Table table3 = new Table();
			Column column17 = new Column();
			ColumnExpression columnExpression17 = new ColumnExpression();
			Table table4 = new Table();
			Join join = new Join();
			RelationColumnInfo relationColumnInfo = new RelationColumnInfo();
			Join join1 = new Join();
			RelationColumnInfo relationColumnInfo1 = new RelationColumnInfo();
			Join join2 = new Join();
			RelationColumnInfo relationColumnInfo2 = new RelationColumnInfo();
			Join join3 = new Join();
			RelationColumnInfo relationColumnInfo3 = new RelationColumnInfo();
			SelectQuery selectQuery1 = new SelectQuery();
			Column column18 = new Column();
			ColumnExpression columnExpression18 = new ColumnExpression();
			Table table5 = new Table();
			Column column19 = new Column();
			ColumnExpression columnExpression19 = new ColumnExpression();
			Column column20 = new Column();
			ColumnExpression columnExpression20 = new ColumnExpression();
			Column column21 = new Column();
			ColumnExpression columnExpression21 = new ColumnExpression();
			Table table6 = new Table();
			Column column22 = new Column();
			ColumnExpression columnExpression22 = new ColumnExpression();
			Join join4 = new Join();
			RelationColumnInfo relationColumnInfo4 = new RelationColumnInfo();
			MasterDetailInfo masterDetailInfo = new MasterDetailInfo();
			RelationColumnInfo relationColumnInfo5 = new RelationColumnInfo();
			ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(RSSReport));
			DynamicListLookUpSettings dynamicListLookUpSetting = new DynamicListLookUpSettings();
			this.sqlDataSource1 = new SqlDataSource(this.components);
			this.Detail = new DetailBand();
			this.xrLabel5 = new XRLabel();
			this.xrLabel4 = new XRLabel();
			this.xrTable2 = new XRTable();
			this.xrTableRow3 = new XRTableRow();
			this.xrTableCell5 = new XRTableCell();
			this.xrTableCell6 = new XRTableCell();
			this.xrTableCell7 = new XRTableCell();
			this.xrTableCell14 = new XRTableCell();
			this.xrTableRow4 = new XRTableRow();
			this.xrTableCell8 = new XRTableCell();
			this.xrTableCell9 = new XRTableCell();
			this.xrTableCell10 = new XRTableCell();
			this.xrTableCell15 = new XRTableCell();
			this.xrTableRow5 = new XRTableRow();
			this.xrTableCell11 = new XRTableCell();
			this.xrTableCell12 = new XRTableCell();
			this.xrLabel44 = new XRLabel();
			this.xrLabel45 = new XRLabel();
			this.xrLabel1 = new XRLabel();
			this.xrLabel2 = new XRLabel();
			this.xrLabel3 = new XRLabel();
			this.xrLabel9 = new XRLabel();
			this.xrLabel11 = new XRLabel();
			this.xrLabel12 = new XRLabel();
			this.xrLabel19 = new XRLabel();
			this.xrLabel20 = new XRLabel();
			this.xrLabel21 = new XRLabel();
			this.xrLabel27 = new XRLabel();
			this.xrLabel29 = new XRLabel();
			this.xrLabel30 = new XRLabel();
			this.TopMargin = new TopMarginBand();
			this.xrLine2 = new XRLine();
			this.xrLabel17 = new XRLabel();
			this.xrLabel18 = new XRLabel();
			this.xrPictureBox1 = new XRPictureBox();
			this.xrLabel22 = new XRLabel();
			this.xrLabel23 = new XRLabel();
			this.xrLabel24 = new XRLabel();
			this.xrLine3 = new XRLine();
			this.xrLabel25 = new XRLabel();
			this.BottomMargin = new BottomMarginBand();
			this.xrPageInfo3 = new XRPageInfo();
			this.xrPageInfo4 = new XRPageInfo();
			this.xrPictureBox2 = new XRPictureBox();
			this.pageFooterBand1 = new PageFooterBand();
			this.reportHeaderBand1 = new ReportHeaderBand();
			this.xrLabel37 = new XRLabel();
			this.Title = new XRControlStyle();
			this.FieldCaption = new XRControlStyle();
			this.PageInfo = new XRControlStyle();
			this.DataField = new XRControlStyle();
			this.xrTable1 = new XRTable();
			this.xrTableRow1 = new XRTableRow();
			this.xrTableCell1 = new XRTableCell();
			this.xrTableCell2 = new XRTableCell();
			this.xrTableRow2 = new XRTableRow();
			this.xrTableCell3 = new XRTableCell();
			this.xrTableCell4 = new XRTableCell();
			this.DetailReport = new DetailReportBand();
			this.Detail1 = new DetailBand();
			this.xrTable4 = new XRTable();
			this.xrTableRow7 = new XRTableRow();
			this.xrTableCell17 = new XRTableCell();
			this.xrTableCell18 = new XRTableCell();
			this.GroupHeader1 = new GroupHeaderBand();
			this.xrTable3 = new XRTable();
			this.xrTableRow6 = new XRTableRow();
			this.xrTableCell13 = new XRTableCell();
			this.xrTableCell16 = new XRTableCell();
			this.DetailReport1 = new DetailReportBand();
			this.Detail2 = new DetailBand();
			this.xrLine8 = new XRLine();
			this.xrLine7 = new XRLine();
			this.xrLabel16 = new XRLabel();
			this.xrLabel13 = new XRLabel();
			this.xrLabel15 = new XRLabel();
			this.xrLine5 = new XRLine();
			this.xrLine6 = new XRLine();
			this.xrTable5 = new XRTable();
			this.xrTableRow8 = new XRTableRow();
			this.xrTableCell19 = new XRTableCell();
			this.xrTableCell20 = new XRTableCell();
			this.xrTableCell21 = new XRTableCell();
			this.xrTableCell22 = new XRTableCell();
			this.xrTableRow9 = new XRTableRow();
			this.xrTableCell23 = new XRTableCell();
			this.xrTableCell24 = new XRTableCell();
			this.xrTableCell25 = new XRTableCell();
			this.xrTableCell26 = new XRTableCell();
			this.xrTableRow10 = new XRTableRow();
			this.xrTableCell27 = new XRTableCell();
			this.xrTableCell29 = new XRTableCell();
			this.xrTableCell30 = new XRTableCell();
			this.xrTableCell28 = new XRTableCell();
			this.xrLabel10 = new XRLabel();
			this.xrLine4 = new XRLine();
			this.xrLine1 = new XRLine();
			this.xrLabel14 = new XRLabel();
			this.xrLabel8 = new XRLabel();
			this.xrLabel7 = new XRLabel();
			this.xrLabel6 = new XRLabel();
			this.PageHeader = new PageHeaderBand();
			this.RSSID = new Parameter();
			((ISupportInitialize)this.xrTable2).BeginInit();
			((ISupportInitialize)this.xrTable1).BeginInit();
			((ISupportInitialize)this.xrTable4).BeginInit();
			((ISupportInitialize)this.xrTable3).BeginInit();
			((ISupportInitialize)this.xrTable5).BeginInit();
			((ISupportInitialize)this).BeginInit();
			this.sqlDataSource1.ConnectionName = "localhost_LabSys_Connection";
			this.sqlDataSource1.Name = "sqlDataSource1";
			columnExpression.ColumnName = "RSSMasterId";
			table.MetaSerializable = "30|30|125|320";
			table.Name = "RSSMaster";
			columnExpression.Table = table;
			column.Expression = columnExpression;
			columnExpression1.ColumnName = "FKJobOrderMasterID";
			columnExpression1.Table = table;
			column1.Expression = columnExpression1;
			columnExpression2.ColumnName = "RSSNumber";
			columnExpression2.Table = table;
			column2.Expression = columnExpression2;
			columnExpression3.ColumnName = "RSSDate";
			columnExpression3.Table = table;
			column3.Expression = columnExpression3;
			columnExpression4.ColumnName = "ContactPersonAtSite";
			columnExpression4.Table = table;
			column4.Expression = columnExpression4;
			columnExpression5.ColumnName = "ContactMobile";
			columnExpression5.Table = table;
			column5.Expression = columnExpression5;
			columnExpression6.ColumnName = "RequestDate";
			columnExpression6.Table = table;
			column6.Expression = columnExpression6;
			columnExpression7.ColumnName = "RequestBy";
			columnExpression7.Table = table;
			column7.Expression = columnExpression7;
			columnExpression8.ColumnName = "RequestTestDate";
			columnExpression8.Table = table;
			column8.Expression = columnExpression8;
			columnExpression9.ColumnName = "TestTime";
			columnExpression9.Table = table;
			column9.Expression = columnExpression9;
			columnExpression10.ColumnName = "SiteLocation";
			columnExpression10.Table = table;
			column10.Expression = columnExpression10;
			columnExpression11.ColumnName = "FkEmpId";
			columnExpression11.Table = table;
			column11.Expression = columnExpression11;
			columnExpression12.ColumnName = "Note";
			columnExpression12.Table = table;
			column12.Expression = columnExpression12;
			columnExpression13.ColumnName = "ReportedBy";
			columnExpression13.Table = table;
			column13.Expression = columnExpression13;
			columnExpression14.ColumnName = "EmpName";
			table1.MetaSerializable = "185|30|125|220";
			table1.Name = "EmployeesList";
			columnExpression14.Table = table1;
			column14.Expression = columnExpression14;
			columnExpression15.ColumnName = "JobOrderNumber";
			table2.MetaSerializable = "340|30|125|360";
			table2.Name = "JobOrderMaster";
			columnExpression15.Table = table2;
			column15.Expression = columnExpression15;
			columnExpression16.ColumnName = "ProjectName";
			table3.MetaSerializable = "495|30|125|280";
			table3.Name = "ProjectsList";
			columnExpression16.Table = table3;
			column16.Expression = columnExpression16;
			columnExpression17.ColumnName = "ContractorName";
			table4.MetaSerializable = "650|30|125|320";
			table4.Name = "ContractorsList";
			columnExpression17.Table = table4;
			column17.Expression = columnExpression17;
			selectQuery.Columns.Add(column);
			selectQuery.Columns.Add(column1);
			selectQuery.Columns.Add(column2);
			selectQuery.Columns.Add(column3);
			selectQuery.Columns.Add(column4);
			selectQuery.Columns.Add(column5);
			selectQuery.Columns.Add(column6);
			selectQuery.Columns.Add(column7);
			selectQuery.Columns.Add(column8);
			selectQuery.Columns.Add(column9);
			selectQuery.Columns.Add(column10);
			selectQuery.Columns.Add(column11);
			selectQuery.Columns.Add(column12);
			selectQuery.Columns.Add(column13);
			selectQuery.Columns.Add(column14);
			selectQuery.Columns.Add(column15);
			selectQuery.Columns.Add(column16);
			selectQuery.Columns.Add(column17);
			selectQuery.Name = "RSSMaster";
			relationColumnInfo.NestedKeyColumn = "EmpID";
			relationColumnInfo.ParentKeyColumn = "FkEmpId";
			join.KeyColumns.Add(relationColumnInfo);
			join.Nested = table1;
			join.Parent = table;
			relationColumnInfo1.NestedKeyColumn = "JobOrderMasterID";
			relationColumnInfo1.ParentKeyColumn = "FKJobOrderMasterID";
			join1.KeyColumns.Add(relationColumnInfo1);
			join1.Nested = table2;
			join1.Parent = table;
			relationColumnInfo2.NestedKeyColumn = "ProjectID";
			relationColumnInfo2.ParentKeyColumn = "FKProjectID";
			join2.KeyColumns.Add(relationColumnInfo2);
			join2.Nested = table3;
			join2.Parent = table2;
			relationColumnInfo3.NestedKeyColumn = "ContractorID";
			relationColumnInfo3.ParentKeyColumn = "FKContractorID";
			join3.KeyColumns.Add(relationColumnInfo3);
			join3.Nested = table4;
			join3.Parent = table3;
			selectQuery.Relations.Add(join);
			selectQuery.Relations.Add(join1);
			selectQuery.Relations.Add(join2);
			selectQuery.Relations.Add(join3);
			selectQuery.Tables.Add(table);
			selectQuery.Tables.Add(table1);
			selectQuery.Tables.Add(table2);
			selectQuery.Tables.Add(table3);
			selectQuery.Tables.Add(table4);
			columnExpression18.ColumnName = "RSSDteailsId";
			table5.MetaSerializable = "30|30|125|100";
			table5.Name = "RSSDetails";
			columnExpression18.Table = table5;
			column18.Expression = columnExpression18;
			columnExpression19.ColumnName = "FkRSSMasterId";
			columnExpression19.Table = table5;
			column19.Expression = columnExpression19;
			columnExpression20.ColumnName = "FkTestId";
			columnExpression20.Table = table5;
			column20.Expression = columnExpression20;
			columnExpression21.ColumnName = "StandardNumber";
			table6.MetaSerializable = "185|30|125|480";
			table6.Name = "TestsList";
			columnExpression21.Table = table6;
			column21.Expression = columnExpression21;
			columnExpression22.ColumnName = "TestName";
			columnExpression22.Table = table6;
			column22.Expression = columnExpression22;
			selectQuery1.Columns.Add(column18);
			selectQuery1.Columns.Add(column19);
			selectQuery1.Columns.Add(column20);
			selectQuery1.Columns.Add(column21);
			selectQuery1.Columns.Add(column22);
			selectQuery1.Name = "RSSDetails";
			relationColumnInfo4.NestedKeyColumn = "TestID";
			relationColumnInfo4.ParentKeyColumn = "FkTestId";
			join4.KeyColumns.Add(relationColumnInfo4);
			join4.Nested = table6;
			join4.Parent = table5;
			selectQuery1.Relations.Add(join4);
			selectQuery1.Tables.Add(table5);
			selectQuery1.Tables.Add(table6);
			this.sqlDataSource1.Queries.AddRange(new SqlQuery[] { selectQuery, selectQuery1 });
			masterDetailInfo.DetailQueryName = "RSSDetails";
			relationColumnInfo5.NestedKeyColumn = "FkRSSMasterId";
			relationColumnInfo5.ParentKeyColumn = "RSSMasterId";
			masterDetailInfo.KeyColumns.Add(relationColumnInfo5);
			masterDetailInfo.MasterQueryName = "RSSMaster";
			masterDetailInfo.Name = "FK_RSSDetails_RSSMaster";
			this.sqlDataSource1.Relations.AddRange(new MasterDetailInfo[] { masterDetailInfo });
			this.sqlDataSource1.ResultSchemaSerializable = componentResourceManager.GetString("sqlDataSource1.ResultSchemaSerializable");
			XRControlCollection controls = this.Detail.Controls;
			XRControl[] xRControlArrays = new XRControl[] { this.xrLabel5, this.xrLabel4, this.xrTable2, this.xrLabel44, this.xrLabel45, this.xrLabel1, this.xrLabel2, this.xrLabel3, this.xrLabel9, this.xrLabel11, this.xrLabel12, this.xrLabel19, this.xrLabel20, this.xrLabel21, this.xrLabel27, this.xrLabel29, this.xrLabel30 };
			controls.AddRange(xRControlArrays);
			this.Detail.Dpi = 100f;
			this.Detail.HeightF = 262.9167f;
			this.Detail.KeepTogether = true;
			this.Detail.KeepTogetherWithDetailReports = true;
			this.Detail.Name = "Detail";
			this.Detail.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.Detail.PageBreak = DevExpress.XtraReports.UI.PageBreak.BeforeBand;
			this.Detail.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLabel5.Dpi = 100f;
			this.xrLabel5.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Italic);
			this.xrLabel5.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel5.LocationFloat = new PointFloat(6.00001f, 234.9167f);
			this.xrLabel5.Name = "xrLabel5";
			this.xrLabel5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel5.SizeF = new System.Drawing.SizeF(306.978f, 18f);
			this.xrLabel5.StyleName = "FieldCaption";
			this.xrLabel5.StylePriority.UseFont = false;
			this.xrLabel5.StylePriority.UseForeColor = false;
			this.xrLabel5.Text = "Test's Requested Information";
			this.xrLabel4.Dpi = 100f;
			this.xrLabel4.Font = new System.Drawing.Font("Arial", 9f, FontStyle.Italic);
			this.xrLabel4.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel4.LocationFloat = new PointFloat(6.00001f, 117.7083f);
			this.xrLabel4.Name = "xrLabel4";
			this.xrLabel4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel4.SizeF = new System.Drawing.SizeF(162f, 18f);
			this.xrLabel4.StyleName = "FieldCaption";
			this.xrLabel4.StylePriority.UseFont = false;
			this.xrLabel4.StylePriority.UseForeColor = false;
			this.xrLabel4.Text = "Ordering Information";
			this.xrTable2.Borders = BorderSide.All;
			this.xrTable2.Dpi = 100f;
			this.xrTable2.Font = new System.Drawing.Font("Arial", 9.75f);
			this.xrTable2.LocationFloat = new PointFloat(21.62507f, 148.9583f);
			this.xrTable2.Name = "xrTable2";
			this.xrTable2.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection rows = this.xrTable2.Rows;
			XRTableRow[] xRTableRowArray = new XRTableRow[] { this.xrTableRow3, this.xrTableRow4, this.xrTableRow5 };
			rows.AddRange(xRTableRowArray);
			this.xrTable2.SizeF = new System.Drawing.SizeF(818.3749f, 75.00002f);
			this.xrTable2.StylePriority.UseBorders = false;
			this.xrTable2.StylePriority.UseFont = false;
			this.xrTable2.StylePriority.UsePadding = false;
			XRTableCellCollection cells = this.xrTableRow3.Cells;
			XRTableCell[] xRTableCellArray = new XRTableCell[] { this.xrTableCell5, this.xrTableCell6, this.xrTableCell7, this.xrTableCell14 };
			cells.AddRange(xRTableCellArray);
			this.xrTableRow3.Dpi = 100f;
			this.xrTableRow3.Name = "xrTableRow3";
			this.xrTableRow3.Weight = 1;
			this.xrTableCell5.Dpi = 100f;
			this.xrTableCell5.Name = "xrTableCell5";
			this.xrTableCell5.Text = "Requested Test Date :";
			this.xrTableCell5.Weight = 0.669738532929508;
			XRBindingCollection dataBindings = this.xrTableCell6.DataBindings;
			XRBinding[] xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.RequestTestDate", "{0:dd MMM yyyy}") };
			dataBindings.AddRange(xRBinding);
			this.xrTableCell6.Dpi = 100f;
			this.xrTableCell6.Name = "xrTableCell6";
			this.xrTableCell6.Weight = 1.33026146707049;
			this.xrTableCell7.Dpi = 100f;
			this.xrTableCell7.Name = "xrTableCell7";
			this.xrTableCell7.Text = "Site Location :";
			this.xrTableCell7.Weight = 0.573909543551371;
			XRBindingCollection xRBindingCollections = this.xrTableCell14.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.SiteLocation") };
			xRBindingCollections.AddRange(xRBinding);
			this.xrTableCell14.Dpi = 100f;
			this.xrTableCell14.Name = "xrTableCell14";
			this.xrTableCell14.Weight = 1.42609045644863;
			XRTableCellCollection xRTableCellCollections = this.xrTableRow4.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell8, this.xrTableCell9, this.xrTableCell10, this.xrTableCell15 };
			xRTableCellCollections.AddRange(xRTableCellArray);
			this.xrTableRow4.Dpi = 100f;
			this.xrTableRow4.Name = "xrTableRow4";
			this.xrTableRow4.Weight = 1;
			this.xrTableCell8.Dpi = 100f;
			this.xrTableCell8.Name = "xrTableCell8";
			this.xrTableCell8.Text = "Testing time @ Site :";
			this.xrTableCell8.Weight = 0.669738532929508;
			XRBindingCollection dataBindings1 = this.xrTableCell9.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.TestTime", "{0:hh:mm tt}") };
			dataBindings1.AddRange(xRBinding);
			this.xrTableCell9.Dpi = 100f;
			this.xrTableCell9.Name = "xrTableCell9";
			this.xrTableCell9.Weight = 1.33026146707049;
			this.xrTableCell10.Dpi = 100f;
			this.xrTableCell10.Name = "xrTableCell10";
			this.xrTableCell10.Text = "Technician Name :";
			this.xrTableCell10.Weight = 0.573910129953254;
			XRBindingCollection xRBindingCollections1 = this.xrTableCell15.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.EmpName") };
			xRBindingCollections1.AddRange(xRBinding);
			this.xrTableCell15.Dpi = 100f;
			this.xrTableCell15.Name = "xrTableCell15";
			this.xrTableCell15.Weight = 1.42608987004675;
			XRTableCellCollection cells1 = this.xrTableRow5.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell11, this.xrTableCell12 };
			cells1.AddRange(xRTableCellArray);
			this.xrTableRow5.Dpi = 100f;
			this.xrTableRow5.Name = "xrTableRow5";
			this.xrTableRow5.Weight = 1;
			this.xrTableCell11.Dpi = 100f;
			this.xrTableCell11.Name = "xrTableCell11";
			this.xrTableCell11.Text = "Note :";
			this.xrTableCell11.Weight = 0.669738532929508;
			XRBindingCollection dataBindings2 = this.xrTableCell12.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.Note") };
			dataBindings2.AddRange(xRBinding);
			this.xrTableCell12.Dpi = 100f;
			this.xrTableCell12.Name = "xrTableCell12";
			this.xrTableCell12.Weight = 3.33026146707049;
			this.xrLabel44.Dpi = 100f;
			this.xrLabel44.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel44.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel44.LocationFloat = new PointFloat(21.62507f, 10.00001f);
			this.xrLabel44.Name = "xrLabel44";
			this.xrLabel44.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel44.SizeF = new System.Drawing.SizeF(151.1616f, 18f);
			this.xrLabel44.StyleName = "FieldCaption";
			this.xrLabel44.StylePriority.UseFont = false;
			this.xrLabel44.StylePriority.UseForeColor = false;
			this.xrLabel44.Text = "Job Order Number";
			XRBindingCollection xRBindingCollections2 = this.xrLabel45.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.JobOrderNumber") };
			xRBindingCollections2.AddRange(xRBinding);
			this.xrLabel45.Dpi = 100f;
			this.xrLabel45.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel45.LocationFloat = new PointFloat(172.7868f, 10.00001f);
			this.xrLabel45.Name = "xrLabel45";
			this.xrLabel45.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel45.SizeF = new System.Drawing.SizeF(267.4276f, 18f);
			this.xrLabel45.StyleName = "DataField";
			this.xrLabel45.StylePriority.UseFont = false;
			this.xrLabel45.StylePriority.UseTextAlignment = false;
			this.xrLabel45.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLabel1.Dpi = 100f;
			this.xrLabel1.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel1.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel1.LocationFloat = new PointFloat(21.62507f, 36.08335f);
			this.xrLabel1.Name = "xrLabel1";
			this.xrLabel1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel1.SizeF = new System.Drawing.SizeF(151.1616f, 18f);
			this.xrLabel1.StyleName = "FieldCaption";
			this.xrLabel1.StylePriority.UseFont = false;
			this.xrLabel1.StylePriority.UseForeColor = false;
			this.xrLabel1.Text = "Project Contractor:";
			this.xrLabel2.Dpi = 100f;
			this.xrLabel2.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel2.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel2.LocationFloat = new PointFloat(21.62507f, 60.08332f);
			this.xrLabel2.Name = "xrLabel2";
			this.xrLabel2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel2.SizeF = new System.Drawing.SizeF(151.1616f, 18f);
			this.xrLabel2.StyleName = "FieldCaption";
			this.xrLabel2.StylePriority.UseFont = false;
			this.xrLabel2.StylePriority.UseForeColor = false;
			this.xrLabel2.Text = "Contact Person @Site";
			this.xrLabel3.Dpi = 100f;
			this.xrLabel3.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel3.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel3.LocationFloat = new PointFloat(21.62507f, 84.08334f);
			this.xrLabel3.Name = "xrLabel3";
			this.xrLabel3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel3.SizeF = new System.Drawing.SizeF(151.1616f, 18f);
			this.xrLabel3.StyleName = "FieldCaption";
			this.xrLabel3.StylePriority.UseFont = false;
			this.xrLabel3.StylePriority.UseForeColor = false;
			this.xrLabel3.Text = "Contact Mobile";
			this.xrLabel9.Dpi = 100f;
			this.xrLabel9.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel9.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel9.LocationFloat = new PointFloat(449.8833f, 36.08335f);
			this.xrLabel9.Name = "xrLabel9";
			this.xrLabel9.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel9.SizeF = new System.Drawing.SizeF(93.24997f, 18f);
			this.xrLabel9.StyleName = "FieldCaption";
			this.xrLabel9.StylePriority.UseFont = false;
			this.xrLabel9.StylePriority.UseForeColor = false;
			this.xrLabel9.Text = "Project Name";
			this.xrLabel11.Dpi = 100f;
			this.xrLabel11.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel11.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel11.LocationFloat = new PointFloat(449.8833f, 84.08334f);
			this.xrLabel11.Name = "xrLabel11";
			this.xrLabel11.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel11.SizeF = new System.Drawing.SizeF(93.24997f, 18f);
			this.xrLabel11.StyleName = "FieldCaption";
			this.xrLabel11.StylePriority.UseFont = false;
			this.xrLabel11.StylePriority.UseForeColor = false;
			this.xrLabel11.Text = "Request By";
			this.xrLabel12.Dpi = 100f;
			this.xrLabel12.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel12.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel12.LocationFloat = new PointFloat(449.8833f, 60.08332f);
			this.xrLabel12.Name = "xrLabel12";
			this.xrLabel12.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel12.SizeF = new System.Drawing.SizeF(93.24997f, 18f);
			this.xrLabel12.StyleName = "FieldCaption";
			this.xrLabel12.StylePriority.UseFont = false;
			this.xrLabel12.StylePriority.UseForeColor = false;
			this.xrLabel12.Text = "Request Date";
			XRBindingCollection dataBindings3 = this.xrLabel19.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.ContractorName") };
			dataBindings3.AddRange(xRBinding);
			this.xrLabel19.Dpi = 100f;
			this.xrLabel19.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel19.LocationFloat = new PointFloat(172.7868f, 36.08335f);
			this.xrLabel19.Name = "xrLabel19";
			this.xrLabel19.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel19.SizeF = new System.Drawing.SizeF(267.4276f, 18f);
			this.xrLabel19.StyleName = "DataField";
			this.xrLabel19.StylePriority.UseFont = false;
			this.xrLabel19.StylePriority.UseTextAlignment = false;
			this.xrLabel19.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRBindingCollection xRBindingCollections3 = this.xrLabel20.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.ContactPersonAtSite") };
			xRBindingCollections3.AddRange(xRBinding);
			this.xrLabel20.Dpi = 100f;
			this.xrLabel20.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel20.LocationFloat = new PointFloat(172.7868f, 60.08332f);
			this.xrLabel20.Name = "xrLabel20";
			this.xrLabel20.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel20.SizeF = new System.Drawing.SizeF(267.4276f, 18f);
			this.xrLabel20.StyleName = "DataField";
			this.xrLabel20.StylePriority.UseFont = false;
			this.xrLabel20.StylePriority.UseTextAlignment = false;
			this.xrLabel20.Text = "xrLabel20";
			this.xrLabel20.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRBindingCollection dataBindings4 = this.xrLabel21.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.ContactMobile") };
			dataBindings4.AddRange(xRBinding);
			this.xrLabel21.Dpi = 100f;
			this.xrLabel21.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel21.LocationFloat = new PointFloat(172.7868f, 84.08334f);
			this.xrLabel21.Name = "xrLabel21";
			this.xrLabel21.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel21.SizeF = new System.Drawing.SizeF(267.4276f, 18f);
			this.xrLabel21.StyleName = "DataField";
			this.xrLabel21.StylePriority.UseFont = false;
			this.xrLabel21.StylePriority.UseTextAlignment = false;
			this.xrLabel21.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRBindingCollection xRBindingCollections4 = this.xrLabel27.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.ProjectName") };
			xRBindingCollections4.AddRange(xRBinding);
			this.xrLabel27.Dpi = 100f;
			this.xrLabel27.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel27.LocationFloat = new PointFloat(543.1333f, 36.08335f);
			this.xrLabel27.Name = "xrLabel27";
			this.xrLabel27.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel27.SizeF = new System.Drawing.SizeF(296.8669f, 18f);
			this.xrLabel27.StyleName = "DataField";
			this.xrLabel27.StylePriority.UseFont = false;
			this.xrLabel27.StylePriority.UseTextAlignment = false;
			this.xrLabel27.Text = "xrLabel27";
			this.xrLabel27.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRBindingCollection dataBindings5 = this.xrLabel29.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.RequestBy") };
			dataBindings5.AddRange(xRBinding);
			this.xrLabel29.Dpi = 100f;
			this.xrLabel29.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel29.LocationFloat = new PointFloat(543.1334f, 84.08331f);
			this.xrLabel29.Name = "xrLabel29";
			this.xrLabel29.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel29.SizeF = new System.Drawing.SizeF(296.8668f, 18.00002f);
			this.xrLabel29.StyleName = "DataField";
			this.xrLabel29.StylePriority.UseFont = false;
			this.xrLabel29.StylePriority.UseTextAlignment = false;
			this.xrLabel29.Text = "xrLabel29";
			this.xrLabel29.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRBindingCollection xRBindingCollections5 = this.xrLabel30.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.RequestDate", "{0:dd MMM yyyy}") };
			xRBindingCollections5.AddRange(xRBinding);
			this.xrLabel30.Dpi = 100f;
			this.xrLabel30.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel30.LocationFloat = new PointFloat(543.1334f, 60.08332f);
			this.xrLabel30.Name = "xrLabel30";
			this.xrLabel30.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel30.SizeF = new System.Drawing.SizeF(296.8668f, 18f);
			this.xrLabel30.StyleName = "DataField";
			this.xrLabel30.StylePriority.UseFont = false;
			this.xrLabel30.StylePriority.UseTextAlignment = false;
			this.xrLabel30.Text = "xrLabel30";
			this.xrLabel30.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRControlCollection xRControlCollection = this.TopMargin.Controls;
			xRControlArrays = new XRControl[] { this.xrLine2, this.xrLabel17, this.xrLabel18, this.xrPictureBox1, this.xrLabel22, this.xrLabel23, this.xrLabel24, this.xrLine3, this.xrLabel25 };
			xRControlCollection.AddRange(xRControlArrays);
			this.TopMargin.Dpi = 100f;
			this.TopMargin.HeightF = 108.125f;
			this.TopMargin.Name = "TopMargin";
			this.TopMargin.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.TopMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLine2.Dpi = 100f;
			this.xrLine2.ForeColor = Color.FromArgb(32, 150, 159);
			this.xrLine2.LocationFloat = new PointFloat(542.1331f, 88.54166f);
			this.xrLine2.Name = "xrLine2";
			this.xrLine2.SizeF = new System.Drawing.SizeF(300.4026f, 13f);
			this.xrLine2.StylePriority.UseForeColor = false;
			this.xrLabel17.BackColor = Color.White;
			this.xrLabel17.Dpi = 100f;
			this.xrLabel17.Font = new System.Drawing.Font("Times New Roman", 11f, FontStyle.Bold);
			this.xrLabel17.ForeColor = Color.FromArgb(45, 84, 108);
			this.xrLabel17.LocationFloat = new PointFloat(567.4379f, 60.58336f);
			this.xrLabel17.Name = "xrLabel17";
			this.xrLabel17.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel17.SizeF = new System.Drawing.SizeF(249.9936f, 22.99997f);
			this.xrLabel17.StylePriority.UseBackColor = false;
			this.xrLabel17.StylePriority.UseFont = false;
			this.xrLabel17.StylePriority.UseForeColor = false;
			this.xrLabel17.StylePriority.UsePadding = false;
			this.xrLabel17.StylePriority.UseTextAlignment = false;
			this.xrLabel17.Text = "اختبارات مواقع - تصميم خلطات - دراسات تربة";
			this.xrLabel17.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrLabel18.BackColor = Color.White;
			this.xrLabel18.Dpi = 100f;
			this.xrLabel18.Font = new System.Drawing.Font("Times New Roman", 11f, FontStyle.Bold);
			this.xrLabel18.ForeColor = Color.FromArgb(45, 84, 108);
			this.xrLabel18.LocationFloat = new PointFloat(567.4379f, 6.58334f);
			this.xrLabel18.Name = "xrLabel18";
			this.xrLabel18.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel18.SizeF = new System.Drawing.SizeF(249.9937f, 24f);
			this.xrLabel18.StylePriority.UseBackColor = false;
			this.xrLabel18.StylePriority.UseFont = false;
			this.xrLabel18.StylePriority.UseForeColor = false;
			this.xrLabel18.StylePriority.UsePadding = false;
			this.xrLabel18.StylePriority.UseTextAlignment = false;
			this.xrLabel18.Text = "إختبارات ميكانيكية وفزيائية  وكميائية لمواد البناء";
			this.xrLabel18.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrPictureBox1.Dpi = 100f;
			this.xrPictureBox1.Image = (Image)componentResourceManager.GetObject("xrPictureBox1.Image");
			this.xrPictureBox1.LocationFloat = new PointFloat(342.5699f, 6.58334f);
			this.xrPictureBox1.Name = "xrPictureBox1";
			this.xrPictureBox1.SizeF = new System.Drawing.SizeF(189.2164f, 94.95832f);
			this.xrLabel22.BackColor = Color.White;
			this.xrLabel22.Dpi = 100f;
			this.xrLabel22.Font = new System.Drawing.Font("Times New Roman", 11f, FontStyle.Bold);
			this.xrLabel22.ForeColor = Color.FromArgb(45, 84, 108);
			this.xrLabel22.LocationFloat = new PointFloat(567.4379f, 32.54168f);
			this.xrLabel22.Name = "xrLabel22";
			this.xrLabel22.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel22.SizeF = new System.Drawing.SizeF(249.9937f, 22.99997f);
			this.xrLabel22.StylePriority.UseBackColor = false;
			this.xrLabel22.StylePriority.UseFont = false;
			this.xrLabel22.StylePriority.UseForeColor = false;
			this.xrLabel22.StylePriority.UsePadding = false;
			this.xrLabel22.StylePriority.UseTextAlignment = false;
			this.xrLabel22.Text = "تربة - اسفلت - حصي - كونكريت - اسمنت - ماء";
			this.xrLabel22.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrLabel23.BackColor = Color.White;
			this.xrLabel23.Dpi = 100f;
			this.xrLabel23.Font = new System.Drawing.Font("Times New Roman", 9f, FontStyle.Bold);
			this.xrLabel23.ForeColor = Color.FromArgb(45, 84, 103);
			this.xrLabel23.LocationFloat = new PointFloat(5.464294f, 30.58335f);
			this.xrLabel23.Name = "xrLabel23";
			this.xrLabel23.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel23.SizeF = new System.Drawing.SizeF(310.5137f, 25f);
			this.xrLabel23.StylePriority.UseBackColor = false;
			this.xrLabel23.StylePriority.UseFont = false;
			this.xrLabel23.StylePriority.UseForeColor = false;
			this.xrLabel23.StylePriority.UsePadding = false;
			this.xrLabel23.StylePriority.UseTextAlignment = false;
			this.xrLabel23.Text = "Soil - Asphalt - Aggregate - Concrete - Cement - Water";
			this.xrLabel23.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLabel24.BackColor = Color.White;
			this.xrLabel24.Dpi = 100f;
			this.xrLabel24.Font = new System.Drawing.Font("Times New Roman", 9f, FontStyle.Bold);
			this.xrLabel24.ForeColor = Color.FromArgb(45, 84, 103);
			this.xrLabel24.LocationFloat = new PointFloat(5.464294f, 55.58335f);
			this.xrLabel24.Name = "xrLabel24";
			this.xrLabel24.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel24.SizeF = new System.Drawing.SizeF(288.8611f, 24f);
			this.xrLabel24.StylePriority.UseBackColor = false;
			this.xrLabel24.StylePriority.UseFont = false;
			this.xrLabel24.StylePriority.UseForeColor = false;
			this.xrLabel24.StylePriority.UsePadding = false;
			this.xrLabel24.StylePriority.UseTextAlignment = false;
			this.xrLabel24.Text = "Site testing - Material design mixes - Soil study";
			this.xrLabel24.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrLine3.Dpi = 100f;
			this.xrLine3.ForeColor = Color.FromArgb(32, 150, 159);
			this.xrLine3.LocationFloat = new PointFloat(6.326614f, 88.54166f);
			this.xrLine3.Name = "xrLine3";
			this.xrLine3.SizeF = new System.Drawing.SizeF(300.4026f, 13f);
			this.xrLine3.StylePriority.UseForeColor = false;
			this.xrLabel25.BackColor = Color.White;
			this.xrLabel25.Dpi = 100f;
			this.xrLabel25.Font = new System.Drawing.Font("Times New Roman", 9f, FontStyle.Bold);
			this.xrLabel25.ForeColor = Color.FromArgb(45, 84, 103);
			this.xrLabel25.LocationFloat = new PointFloat(5.464294f, 6.58334f);
			this.xrLabel25.Name = "xrLabel25";
			this.xrLabel25.Padding = new PaddingInfo(2, 2, 0, 2, 100f);
			this.xrLabel25.SizeF = new System.Drawing.SizeF(285.9722f, 24f);
			this.xrLabel25.StylePriority.UseBackColor = false;
			this.xrLabel25.StylePriority.UseFont = false;
			this.xrLabel25.StylePriority.UseForeColor = false;
			this.xrLabel25.StylePriority.UsePadding = false;
			this.xrLabel25.StylePriority.UseTextAlignment = false;
			this.xrLabel25.Text = "Mechanical , physical and chimical material testing";
			this.xrLabel25.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			XRControlCollection controls1 = this.BottomMargin.Controls;
			xRControlArrays = new XRControl[] { this.xrPageInfo3, this.xrPageInfo4, this.xrPictureBox2 };
			controls1.AddRange(xRControlArrays);
			this.BottomMargin.Dpi = 100f;
			this.BottomMargin.HeightF = 132f;
			this.BottomMargin.Name = "BottomMargin";
			this.BottomMargin.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
			this.BottomMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
			this.xrPageInfo3.Dpi = 100f;
			this.xrPageInfo3.LocationFloat = new PointFloat(10.1633f, 108.5f);
			this.xrPageInfo3.Name = "xrPageInfo3";
			this.xrPageInfo3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrPageInfo3.PageInfo = DevExpress.XtraPrinting.PageInfo.DateTime;
			this.xrPageInfo3.SizeF = new System.Drawing.SizeF(313f, 23f);
			this.xrPageInfo3.StyleName = "PageInfo";
			this.xrPageInfo4.Dpi = 100f;
			this.xrPageInfo4.Format = "Page {0} of {1}";
			this.xrPageInfo4.LocationFloat = new PointFloat(526.8367f, 108.5f);
			this.xrPageInfo4.Name = "xrPageInfo4";
			this.xrPageInfo4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrPageInfo4.SizeF = new System.Drawing.SizeF(313f, 23f);
			this.xrPageInfo4.StyleName = "PageInfo";
			this.xrPageInfo4.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.xrPictureBox2.Dpi = 100f;
			this.xrPictureBox2.Image = (Image)componentResourceManager.GetObject("xrPictureBox2.Image");
			this.xrPictureBox2.LocationFloat = new PointFloat(109.8736f, 0f);
			this.xrPictureBox2.Name = "xrPictureBox2";
			this.xrPictureBox2.SizeF = new System.Drawing.SizeF(581.3381f, 74.20829f);
			this.pageFooterBand1.Dpi = 100f;
			this.pageFooterBand1.HeightF = 0f;
			this.pageFooterBand1.Name = "pageFooterBand1";
			this.reportHeaderBand1.Dpi = 100f;
			this.reportHeaderBand1.HeightF = 1.916663f;
			this.reportHeaderBand1.Name = "reportHeaderBand1";
			this.xrLabel37.Dpi = 100f;
			this.xrLabel37.Font = new System.Drawing.Font("Arial", 20f, FontStyle.Bold | FontStyle.Italic | FontStyle.Underline);
			this.xrLabel37.LocationFloat = new PointFloat(21.62507f, 10.00001f);
			this.xrLabel37.Name = "xrLabel37";
			this.xrLabel37.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel37.SizeF = new System.Drawing.SizeF(534.8749f, 33f);
			this.xrLabel37.StyleName = "Title";
			this.xrLabel37.StylePriority.UseFont = false;
			this.xrLabel37.StylePriority.UseTextAlignment = false;
			this.xrLabel37.Text = "Request for Site Services (R.S.S)";
			this.xrLabel37.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopRight;
			this.Title.BackColor = Color.Transparent;
			this.Title.BorderColor = Color.Black;
			this.Title.Borders = BorderSide.None;
			this.Title.BorderWidth = 1f;
			this.Title.Font = new System.Drawing.Font("Times New Roman", 20f, FontStyle.Bold);
			this.Title.ForeColor = Color.Maroon;
			this.Title.Name = "Title";
			this.FieldCaption.BackColor = Color.Transparent;
			this.FieldCaption.BorderColor = Color.Black;
			this.FieldCaption.Borders = BorderSide.None;
			this.FieldCaption.BorderWidth = 1f;
			this.FieldCaption.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Bold);
			this.FieldCaption.ForeColor = Color.Maroon;
			this.FieldCaption.Name = "FieldCaption";
			this.PageInfo.BackColor = Color.Transparent;
			this.PageInfo.BorderColor = Color.Black;
			this.PageInfo.Borders = BorderSide.None;
			this.PageInfo.BorderWidth = 1f;
			this.PageInfo.Font = new System.Drawing.Font("Times New Roman", 10f, FontStyle.Bold);
			this.PageInfo.ForeColor = Color.Black;
			this.PageInfo.Name = "PageInfo";
			this.DataField.BackColor = Color.Transparent;
			this.DataField.BorderColor = Color.Black;
			this.DataField.Borders = BorderSide.None;
			this.DataField.BorderWidth = 1f;
			this.DataField.Font = new System.Drawing.Font("Times New Roman", 10f);
			this.DataField.ForeColor = Color.Black;
			this.DataField.Name = "DataField";
			this.DataField.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrTable1.Borders = BorderSide.All;
			this.xrTable1.Dpi = 100f;
			this.xrTable1.Font = new System.Drawing.Font("Arial", 11f);
			this.xrTable1.LocationFloat = new PointFloat(606.4586f, 10.00001f);
			this.xrTable1.Name = "xrTable1";
			this.xrTable1.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection xRTableRowCollections = this.xrTable1.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow1, this.xrTableRow2 };
			xRTableRowCollections.AddRange(xRTableRowArray);
			this.xrTable1.SizeF = new System.Drawing.SizeF(224.1664f, 50f);
			this.xrTable1.StylePriority.UseBorders = false;
			this.xrTable1.StylePriority.UseFont = false;
			this.xrTable1.StylePriority.UsePadding = false;
			XRTableCellCollection xRTableCellCollections1 = this.xrTableRow1.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell1, this.xrTableCell2 };
			xRTableCellCollections1.AddRange(xRTableCellArray);
			this.xrTableRow1.Dpi = 100f;
			this.xrTableRow1.Name = "xrTableRow1";
			this.xrTableRow1.Weight = 1;
			this.xrTableCell1.Dpi = 100f;
			this.xrTableCell1.Font = new System.Drawing.Font("Arial", 10f);
			this.xrTableCell1.Multiline = true;
			this.xrTableCell1.Name = "xrTableCell1";
			this.xrTableCell1.StylePriority.UseFont = false;
			this.xrTableCell1.Text = "Request No:";
			this.xrTableCell1.Weight = 0.814126339394382;
			XRBindingCollection dataBindings6 = this.xrTableCell2.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.RSSNumber") };
			dataBindings6.AddRange(xRBinding);
			this.xrTableCell2.Dpi = 100f;
			this.xrTableCell2.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Bold);
			this.xrTableCell2.Name = "xrTableCell2";
			this.xrTableCell2.StylePriority.UseFont = false;
			this.xrTableCell2.Weight = 1.18587366060562;
			XRTableCellCollection cells2 = this.xrTableRow2.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell3, this.xrTableCell4 };
			cells2.AddRange(xRTableCellArray);
			this.xrTableRow2.Dpi = 100f;
			this.xrTableRow2.Name = "xrTableRow2";
			this.xrTableRow2.Weight = 1;
			this.xrTableCell3.Dpi = 100f;
			this.xrTableCell3.Font = new System.Drawing.Font("Arial", 10f);
			this.xrTableCell3.Multiline = true;
			this.xrTableCell3.Name = "xrTableCell3";
			this.xrTableCell3.StylePriority.UseFont = false;
			this.xrTableCell3.Text = "Request Date :";
			this.xrTableCell3.Weight = 0.814126339394382;
			XRBindingCollection xRBindingCollections6 = this.xrTableCell4.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.RSSDate", "{0:dd MMM yyyy}") };
			xRBindingCollections6.AddRange(xRBinding);
			this.xrTableCell4.Dpi = 100f;
			this.xrTableCell4.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Bold);
			this.xrTableCell4.Name = "xrTableCell4";
			this.xrTableCell4.StylePriority.UseFont = false;
			this.xrTableCell4.Weight = 1.18587366060562;
			BandCollection bands = this.DetailReport.Bands;
			DevExpress.XtraReports.UI.Band[] detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail1, this.GroupHeader1 };
			bands.AddRange(detail1);
			this.DetailReport.DataMember = "RSSMaster.FK_RSSDetails_RSSMaster";
			this.DetailReport.DataSource = this.sqlDataSource1;
			this.DetailReport.Dpi = 100f;
			this.DetailReport.Level = 0;
			this.DetailReport.Name = "DetailReport";
			XRControlCollection xRControlCollection1 = this.Detail1.Controls;
			xRControlArrays = new XRControl[] { this.xrTable4 };
			xRControlCollection1.AddRange(xRControlArrays);
			this.Detail1.Dpi = 100f;
			this.Detail1.HeightF = 25f;
			this.Detail1.Name = "Detail1";
			this.xrTable4.Borders = BorderSide.Left | BorderSide.Right | BorderSide.Bottom;
			this.xrTable4.Dpi = 100f;
			this.xrTable4.LocationFloat = new PointFloat(67.70834f, 0f);
			this.xrTable4.Name = "xrTable4";
			this.xrTable4.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection rows1 = this.xrTable4.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow7 };
			rows1.AddRange(xRTableRowArray);
			this.xrTable4.SizeF = new System.Drawing.SizeF(720.8333f, 25f);
			this.xrTable4.StylePriority.UseBorders = false;
			this.xrTable4.StylePriority.UsePadding = false;
			XRTableCellCollection xRTableCellCollections2 = this.xrTableRow7.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell17, this.xrTableCell18 };
			xRTableCellCollections2.AddRange(xRTableCellArray);
			this.xrTableRow7.Dpi = 100f;
			this.xrTableRow7.Name = "xrTableRow7";
			this.xrTableRow7.Weight = 11.5;
			XRBindingCollection dataBindings7 = this.xrTableCell17.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.FK_RSSDetails_RSSMaster.TestName") };
			dataBindings7.AddRange(xRBinding);
			this.xrTableCell17.Dpi = 100f;
			this.xrTableCell17.Name = "xrTableCell17";
			this.xrTableCell17.Text = "xrTableCell17";
			this.xrTableCell17.Weight = 0.208643817200808;
			XRBindingCollection xRBindingCollections7 = this.xrTableCell18.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.FK_RSSDetails_RSSMaster.StandardNumber") };
			xRBindingCollections7.AddRange(xRBinding);
			this.xrTableCell18.Dpi = 100f;
			this.xrTableCell18.Name = "xrTableCell18";
			this.xrTableCell18.Text = "xrTableCell18";
			this.xrTableCell18.Weight = 0.0990484904914996;
			XRControlCollection controls2 = this.GroupHeader1.Controls;
			xRControlArrays = new XRControl[] { this.xrTable3 };
			controls2.AddRange(xRControlArrays);
			this.GroupHeader1.Dpi = 100f;
			this.GroupHeader1.HeightF = 25f;
			this.GroupHeader1.Name = "GroupHeader1";
			this.GroupHeader1.RepeatEveryPage = true;
			this.xrTable3.Borders = BorderSide.All;
			this.xrTable3.Dpi = 100f;
			this.xrTable3.Font = new System.Drawing.Font("Times New Roman", 9.75f, FontStyle.Bold);
			this.xrTable3.LocationFloat = new PointFloat(67.7083f, 0f);
			this.xrTable3.Name = "xrTable3";
			XRTableRowCollection xRTableRowCollections1 = this.xrTable3.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow6 };
			xRTableRowCollections1.AddRange(xRTableRowArray);
			this.xrTable3.SizeF = new System.Drawing.SizeF(720.8333f, 25f);
			this.xrTable3.StylePriority.UseBorders = false;
			this.xrTable3.StylePriority.UseFont = false;
			this.xrTable3.StylePriority.UseTextAlignment = false;
			this.xrTable3.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			XRTableCellCollection cells3 = this.xrTableRow6.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell13, this.xrTableCell16 };
			cells3.AddRange(xRTableCellArray);
			this.xrTableRow6.Dpi = 100f;
			this.xrTableRow6.Name = "xrTableRow6";
			this.xrTableRow6.Weight = 11.5;
			this.xrTableCell13.Dpi = 100f;
			this.xrTableCell13.Name = "xrTableCell13";
			this.xrTableCell13.Text = "Test";
			this.xrTableCell13.Weight = 0.208643830227431;
			this.xrTableCell16.Dpi = 100f;
			this.xrTableCell16.Name = "xrTableCell16";
			this.xrTableCell16.Text = "Standard No";
			this.xrTableCell16.Weight = 0.0990484774648763;
			BandCollection bandCollections = this.DetailReport1.Bands;
			detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail2 };
			bandCollections.AddRange(detail1);
			this.DetailReport1.Dpi = 100f;
			this.DetailReport1.Level = 1;
			this.DetailReport1.Name = "DetailReport1";
			XRControlCollection xRControlCollection2 = this.Detail2.Controls;
			xRControlArrays = new XRControl[] { this.xrLine8, this.xrLine7, this.xrLabel16, this.xrLabel13, this.xrLabel15, this.xrLine5, this.xrLine6, this.xrTable5, this.xrLabel10, this.xrLine4, this.xrLine1, this.xrLabel14, this.xrLabel8, this.xrLabel7, this.xrLabel6 };
			xRControlCollection2.AddRange(xRControlArrays);
			this.Detail2.Dpi = 100f;
			this.Detail2.HeightF = 306.25f;
			this.Detail2.Name = "Detail2";
			this.xrLine8.BorderDashStyle = DevExpress.XtraPrinting.BorderDashStyle.Dot;
			this.xrLine8.Dpi = 100f;
			this.xrLine8.ForeColor = Color.Black;
			this.xrLine8.LineStyle = DashStyle.Dot;
			this.xrLine8.LocationFloat = new PointFloat(109.8736f, 274.2916f);
			this.xrLine8.Name = "xrLine8";
			this.xrLine8.SizeF = new System.Drawing.SizeF(695.418f, 23.00002f);
			this.xrLine8.StylePriority.UseBorderDashStyle = false;
			this.xrLine8.StylePriority.UseForeColor = false;
			this.xrLine7.BorderDashStyle = DevExpress.XtraPrinting.BorderDashStyle.Dot;
			this.xrLine7.Dpi = 100f;
			this.xrLine7.ForeColor = Color.Black;
			this.xrLine7.LineStyle = DashStyle.Dot;
			this.xrLine7.LocationFloat = new PointFloat(109.8736f, 243.8751f);
			this.xrLine7.Name = "xrLine7";
			this.xrLine7.SizeF = new System.Drawing.SizeF(695.418f, 23.00002f);
			this.xrLine7.StylePriority.UseBorderDashStyle = false;
			this.xrLine7.StylePriority.UseForeColor = false;
			this.xrLabel16.Dpi = 100f;
			this.xrLabel16.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel16.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel16.LocationFloat = new PointFloat(65.39562f, 243.8751f);
			this.xrLabel16.Name = "xrLabel16";
			this.xrLabel16.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel16.SizeF = new System.Drawing.SizeF(44.47798f, 18f);
			this.xrLabel16.StyleName = "FieldCaption";
			this.xrLabel16.StylePriority.UseFont = false;
			this.xrLabel16.StylePriority.UseForeColor = false;
			this.xrLabel16.Text = "Note:";
			this.xrLabel13.Dpi = 100f;
			this.xrLabel13.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel13.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel13.LocationFloat = new PointFloat(65.39559f, 208.1875f);
			this.xrLabel13.Name = "xrLabel13";
			this.xrLabel13.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel13.SizeF = new System.Drawing.SizeF(115.7449f, 18f);
			this.xrLabel13.StyleName = "FieldCaption";
			this.xrLabel13.StylePriority.UseFont = false;
			this.xrLabel13.StylePriority.UseForeColor = false;
			this.xrLabel13.Text = "Total Work Time :";
			this.xrLabel15.Dpi = 100f;
			this.xrLabel15.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel15.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel15.LocationFloat = new PointFloat(439.9803f, 208.1875f);
			this.xrLabel15.Name = "xrLabel15";
			this.xrLabel15.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel15.SizeF = new System.Drawing.SizeF(145.5196f, 18f);
			this.xrLabel15.StyleName = "FieldCaption";
			this.xrLabel15.StylePriority.UseFont = false;
			this.xrLabel15.StylePriority.UseForeColor = false;
			this.xrLabel15.Text = "Technician Signature :";
			this.xrLine5.BorderDashStyle = DevExpress.XtraPrinting.BorderDashStyle.Dot;
			this.xrLine5.Dpi = 100f;
			this.xrLine5.ForeColor = Color.Black;
			this.xrLine5.LineStyle = DashStyle.Dot;
			this.xrLine5.LocationFloat = new PointFloat(181.9993f, 208.1875f);
			this.xrLine5.Name = "xrLine5";
			this.xrLine5.SizeF = new System.Drawing.SizeF(185.4167f, 23f);
			this.xrLine5.StylePriority.UseBorderDashStyle = false;
			this.xrLine5.StylePriority.UseForeColor = false;
			this.xrLine6.Dpi = 100f;
			this.xrLine6.ForeColor = Color.Black;
			this.xrLine6.LineStyle = DashStyle.Dot;
			this.xrLine6.LocationFloat = new PointFloat(585.4999f, 208.1875f);
			this.xrLine6.Name = "xrLine6";
			this.xrLine6.SizeF = new System.Drawing.SizeF(219.7917f, 23f);
			this.xrLine6.StylePriority.UseForeColor = false;
			this.xrTable5.Borders = BorderSide.All;
			this.xrTable5.Dpi = 100f;
			this.xrTable5.LocationFloat = new PointFloat(9.999998f, 80.62502f);
			this.xrTable5.Name = "xrTable5";
			this.xrTable5.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
			XRTableRowCollection rows2 = this.xrTable5.Rows;
			xRTableRowArray = new XRTableRow[] { this.xrTableRow8, this.xrTableRow9, this.xrTableRow10 };
			rows2.AddRange(xRTableRowArray);
			this.xrTable5.SizeF = new System.Drawing.SizeF(832.6734f, 109.375f);
			this.xrTable5.StylePriority.UseBorders = false;
			this.xrTable5.StylePriority.UsePadding = false;
			XRTableCellCollection xRTableCellCollections3 = this.xrTableRow8.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell19, this.xrTableCell20, this.xrTableCell21, this.xrTableCell22 };
			xRTableCellCollections3.AddRange(xRTableCellArray);
			this.xrTableRow8.Dpi = 100f;
			this.xrTableRow8.Name = "xrTableRow8";
			this.xrTableRow8.Weight = 1;
			this.xrTableCell19.Dpi = 100f;
			this.xrTableCell19.Name = "xrTableCell19";
			this.xrTableCell19.StylePriority.UseTextAlignment = false;
			this.xrTableCell19.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrTableCell19.Weight = 1.11008020875748;
			this.xrTableCell20.Dpi = 100f;
			this.xrTableCell20.Name = "xrTableCell20";
			this.xrTableCell20.StylePriority.UseTextAlignment = false;
			this.xrTableCell20.Text = "TIME";
			this.xrTableCell20.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrTableCell20.Weight = 0.889919791242519;
			this.xrTableCell21.Dpi = 100f;
			this.xrTableCell21.Multiline = true;
			this.xrTableCell21.Name = "xrTableCell21";
			this.xrTableCell21.StylePriority.UseTextAlignment = false;
			this.xrTableCell21.Text = "APPROVED BY\r\n(CUSTOMER NAME)";
			this.xrTableCell21.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrTableCell21.Weight = 0.949206611058391;
			this.xrTableCell22.Dpi = 100f;
			this.xrTableCell22.Name = "xrTableCell22";
			this.xrTableCell22.StylePriority.UseTextAlignment = false;
			this.xrTableCell22.Text = "CUSTOMER SIGNATURE";
			this.xrTableCell22.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
			this.xrTableCell22.Weight = 1.05079338894161;
			XRTableCellCollection cells4 = this.xrTableRow9.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell23, this.xrTableCell24, this.xrTableCell25, this.xrTableCell26 };
			cells4.AddRange(xRTableCellArray);
			this.xrTableRow9.Dpi = 100f;
			this.xrTableRow9.Name = "xrTableRow9";
			this.xrTableRow9.Weight = 1;
			this.xrTableCell23.Dpi = 100f;
			this.xrTableCell23.Name = "xrTableCell23";
			this.xrTableCell23.Text = "ARRIVAL TIME AT (SITE/LAB)";
			this.xrTableCell23.Weight = 1.11008020875748;
			this.xrTableCell24.Dpi = 100f;
			this.xrTableCell24.Name = "xrTableCell24";
			this.xrTableCell24.Weight = 0.889919791242519;
			this.xrTableCell25.Dpi = 100f;
			this.xrTableCell25.Name = "xrTableCell25";
			this.xrTableCell25.Weight = 0.949207197460274;
			this.xrTableCell26.Dpi = 100f;
			this.xrTableCell26.Name = "xrTableCell26";
			this.xrTableCell26.Weight = 1.05079280253973;
			XRTableCellCollection xRTableCellCollections4 = this.xrTableRow10.Cells;
			xRTableCellArray = new XRTableCell[] { this.xrTableCell27, this.xrTableCell29, this.xrTableCell30, this.xrTableCell28 };
			xRTableCellCollections4.AddRange(xRTableCellArray);
			this.xrTableRow10.Dpi = 100f;
			this.xrTableRow10.Name = "xrTableRow10";
			this.xrTableRow10.Weight = 1;
			this.xrTableCell27.Dpi = 100f;
			this.xrTableCell27.Name = "xrTableCell27";
			this.xrTableCell27.Text = "MOVING TIME AT (SITE/LAB)";
			this.xrTableCell27.Weight = 1.11008020875748;
			this.xrTableCell29.Dpi = 100f;
			this.xrTableCell29.Name = "xrTableCell29";
			this.xrTableCell29.Weight = 0.894367783693567;
			this.xrTableCell30.Dpi = 100f;
			this.xrTableCell30.Name = "xrTableCell30";
			this.xrTableCell30.Weight = 0.944758753738155;
			this.xrTableCell28.Dpi = 100f;
			this.xrTableCell28.Name = "xrTableCell28";
			this.xrTableCell28.Weight = 1.0507932538108;
			this.xrLabel10.Dpi = 100f;
			this.xrLabel10.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Italic);
			this.xrLabel10.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel10.LocationFloat = new PointFloat(0.7511933f, 52.08333f);
			this.xrLabel10.Name = "xrLabel10";
			this.xrLabel10.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel10.SizeF = new System.Drawing.SizeF(306.978f, 18f);
			this.xrLabel10.StyleName = "FieldCaption";
			this.xrLabel10.StylePriority.UseFont = false;
			this.xrLabel10.StylePriority.UseForeColor = false;
			this.xrLabel10.Text = "Servicing Information:";
			this.xrLine4.Dpi = 100f;
			this.xrLine4.ForeColor = Color.Black;
			this.xrLine4.LineStyle = DashStyle.Dot;
			this.xrLine4.LocationFloat = new PointFloat(711.14f, 14.99999f);
			this.xrLine4.Name = "xrLine4";
			this.xrLine4.SizeF = new System.Drawing.SizeF(129.1667f, 23f);
			this.xrLine4.StylePriority.UseForeColor = false;
			this.xrLine1.BorderDashStyle = DevExpress.XtraPrinting.BorderDashStyle.Dot;
			this.xrLine1.Dpi = 100f;
			this.xrLine1.ForeColor = Color.Black;
			this.xrLine1.LineStyle = DashStyle.Dot;
			this.xrLine1.LocationFloat = new PointFloat(382.665f, 14.99999f);
			this.xrLine1.Name = "xrLine1";
			this.xrLine1.SizeF = new System.Drawing.SizeF(129.1667f, 23f);
			this.xrLine1.StylePriority.UseBorderDashStyle = false;
			this.xrLine1.StylePriority.UseForeColor = false;
			XRBindingCollection dataBindings8 = this.xrLabel14.DataBindings;
			xRBinding = new XRBinding[] { new XRBinding("Text", null, "RSSMaster.ReportedBy") };
			dataBindings8.AddRange(xRBinding);
			this.xrLabel14.Dpi = 100f;
			this.xrLabel14.Font = new System.Drawing.Font("Arial", 10f, FontStyle.Underline);
			this.xrLabel14.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel14.LocationFloat = new PointFloat(125.973f, 9.999943f);
			this.xrLabel14.Name = "xrLabel14";
			this.xrLabel14.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel14.SizeF = new System.Drawing.SizeF(137.848f, 18f);
			this.xrLabel14.StyleName = "FieldCaption";
			this.xrLabel14.StylePriority.UseFont = false;
			this.xrLabel14.StylePriority.UseForeColor = false;
			this.xrLabel8.Dpi = 100f;
			this.xrLabel8.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel8.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel8.LocationFloat = new PointFloat(547.9167f, 9.999943f);
			this.xrLabel8.Name = "xrLabel8";
			this.xrLabel8.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel8.SizeF = new System.Drawing.SizeF(145.5196f, 18f);
			this.xrLabel8.StyleName = "FieldCaption";
			this.xrLabel8.StylePriority.UseFont = false;
			this.xrLabel8.StylePriority.UseForeColor = false;
			this.xrLabel8.Text = "Technician Signature :";
			this.xrLabel7.Dpi = 100f;
			this.xrLabel7.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel7.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel7.LocationFloat = new PointFloat(280.2083f, 9.999943f);
			this.xrLabel7.Name = "xrLabel7";
			this.xrLabel7.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel7.SizeF = new System.Drawing.SizeF(86.14462f, 18f);
			this.xrLabel7.StyleName = "FieldCaption";
			this.xrLabel7.StylePriority.UseFont = false;
			this.xrLabel7.StylePriority.UseForeColor = false;
			this.xrLabel7.Text = "Supervisor :";
			this.xrLabel6.Dpi = 100f;
			this.xrLabel6.Font = new System.Drawing.Font("Arial", 10f);
			this.xrLabel6.ForeColor = Color.FromArgb(0, 0, 0);
			this.xrLabel6.LocationFloat = new PointFloat(31.87501f, 10.00001f);
			this.xrLabel6.Name = "xrLabel6";
			this.xrLabel6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
			this.xrLabel6.SizeF = new System.Drawing.SizeF(94.09796f, 18f);
			this.xrLabel6.StyleName = "FieldCaption";
			this.xrLabel6.StylePriority.UseFont = false;
			this.xrLabel6.StylePriority.UseForeColor = false;
			this.xrLabel6.Text = "Reported By:";
			XRControlCollection controls3 = this.PageHeader.Controls;
			xRControlArrays = new XRControl[] { this.xrLabel37, this.xrTable1 };
			controls3.AddRange(xRControlArrays);
			this.PageHeader.Dpi = 100f;
			this.PageHeader.HeightF = 76.04166f;
			this.PageHeader.Name = "PageHeader";
			this.RSSID.Description = "RSSID";
			dynamicListLookUpSetting.DataAdapter = null;
			dynamicListLookUpSetting.DataMember = "RSSMaster";
			dynamicListLookUpSetting.DataSource = this.sqlDataSource1;
			dynamicListLookUpSetting.DisplayMember = "RSSNumber";
			dynamicListLookUpSetting.FilterString = null;
			dynamicListLookUpSetting.ValueMember = "RSSMasterId";
			this.RSSID.LookUpSettings = dynamicListLookUpSetting;
			this.RSSID.Name = "RSSID";
			this.RSSID.Type = typeof(int);
			this.RSSID.ValueInfo = "0";
			BandCollection bands1 = base.Bands;
			detail1 = new DevExpress.XtraReports.UI.Band[] { this.Detail, this.TopMargin, this.BottomMargin, this.pageFooterBand1, this.reportHeaderBand1, this.DetailReport, this.DetailReport1, this.PageHeader };
			bands1.AddRange(detail1);
			base.ComponentStorage.AddRange(new IComponent[] { this.sqlDataSource1 });
			base.DataMember = "RSSMaster";
			base.DataSource = this.sqlDataSource1;
			this.FilterString = "[RSSMasterId] = ?RSSID";
			base.Margins = new System.Drawing.Printing.Margins(0, 2, 108, 132);
			base.Parameters.AddRange(new Parameter[] { this.RSSID });
			XRControlStyleSheet styleSheet = base.StyleSheet;
			XRControlStyle[] title = new XRControlStyle[] { this.Title, this.FieldCaption, this.PageInfo, this.DataField };
			styleSheet.AddRange(title);
			base.Version = "16.1";
			((ISupportInitialize)this.xrTable2).EndInit();
			((ISupportInitialize)this.xrTable1).EndInit();
			((ISupportInitialize)this.xrTable4).EndInit();
			((ISupportInitialize)this.xrTable3).EndInit();
			((ISupportInitialize)this.xrTable5).EndInit();
			((ISupportInitialize)this).EndInit();
		}
	}
}