//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLobalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLobalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GLobalMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total allocated amount is less than selected journal amount.
        /// </summary>
        internal static string AllocatedAmountError {
            get {
                return ResourceManager.GetString("AllocatedAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Code Already Exist.
        /// </summary>
        internal static string CodeExist {
            get {
                return ResourceManager.GetString("CodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Confirmed.
        /// </summary>
        internal static string ConfirmError {
            get {
                return ResourceManager.GetString("ConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter one value, Debit or Credit.
        /// </summary>
        internal static string CriedtAndDepitError {
            get {
                return ResourceManager.GetString("CriedtAndDepitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Segment Value Already Exist.
        /// </summary>
        internal static string DefaultSegmentValueExist {
            get {
                return ResourceManager.GetString("DefaultSegmentValueExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Deleting {0}, It used in Basic Data.
        /// </summary>
        internal static string DeleteBDError {
            get {
                return ResourceManager.GetString("DeleteBDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Deleting {0}, It has Childs.
        /// </summary>
        internal static string DeleteChildError {
            get {
                return ResourceManager.GetString("DeleteChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting {0}.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Deleting {0}, It used in Transaction.
        /// </summary>
        internal static string DeleteTransError {
            get {
                return ResourceManager.GetString("DeleteTransError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Data.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Inserting {0}.
        /// </summary>
        internal static string InsertError {
            get {
                return ResourceManager.GetString("InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Group Used With Item.
        /// </summary>
        internal static string ItemGroupinAction {
            get {
                return ResourceManager.GetString("ItemGroupinAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Save JV, Total Debit not equal Total Credit.
        /// </summary>
        internal static string JVBalanceError {
            get {
                return ResourceManager.GetString("JVBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Date..
        /// </summary>
        internal static string JVDateError {
            get {
                return ResourceManager.GetString("JVDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Not Valid.
        /// </summary>
        internal static string JVNoAccount {
            get {
                return ResourceManager.GetString("JVNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must insert one details for saving.
        /// </summary>
        internal static string JVNoDetailsError {
            get {
                return ResourceManager.GetString("JVNoDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Can&apos;t Be Default.
        /// </summary>
        internal static string ParentNotDefault {
            get {
                return ResourceManager.GetString("ParentNotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Intersect With Another Segment Value.
        /// </summary>
        internal static string RangeIntersect {
            get {
                return ResourceManager.GetString("RangeIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date can&apos;t be grater than the current date.
        /// </summary>
        internal static string RateDate {
            get {
                return ResourceManager.GetString("RateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (From / To) Stores can&apos;t be same.
        /// </summary>
        internal static string SameStoreError {
            get {
                return ResourceManager.GetString("SameStoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updateing {0}.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
    }
}
